`timescale 1ns / 1ps
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Apr 14 2023 13:39:49 IST (Apr 14 2023 08:09:49 UTC)

// Verification Directory fv/flip_flops 

module flip_flops(clk, pc_out_stage_1, pc_in_stage_2,
     instruction_stage_1, instruction_stage_2, pc_out_stage_2,
     pc_in_stage_3, read_data1_stage_2, read_data1_stage_3,
     read_data2_stage_2, read_data2_in_stage_3,
     write_register_out_stage_2, write_register_in_stage_3,
     ALUSrc_stage_2, ALUSrc_stage_3, MemToReg_stage_2,
     MemToReg_in_stage_3, RegWrite_stage_2, RegWrite_in_stage_3,
     MemRead_stage_2, MemRead_in_stage_3, MemWrite_stage_2,
     MemWrite_in_stage_3, Branch_stage_2, Branch_in_stage_3,
     ALUOp_stage_2, ALUOp_stage_3, immediate_stage_2,
     immediate_stage_3, ALU_control_input_stage_2,
     ALU_control_input_stage_3, sum_stage_3, sum_in_stage_4,
     zero_stage_3, zero_stage_4, alu_result_stage_3,
     alu_result_in_stage_4, read_data2_out_stage_3,
     read_data2_in_stage_4, write_register_out_stage_3,
     write_register_in_stage_4, MemToReg_out_stage_3,
     MemToReg_in_stage_4, RegWrite_out_stage_3, RegWrite_in_stage_4,
     MemRead_out_stage_3, MemRead_in_stage_4, MemWrite_out_stage_3,
     MemWrite_in_stage_4, Branch_out_stage_3, Branch_in_stage_4,
     read_data_out_stage_4, read_data_in_stage_5,
     write_register_out_stage_4, write_register_in_stage_5,
     alu_result_out_stage_4, alu_result_in_stage_5,
     MemToReg_out_stage_4, MemToReg_in_stage_5, RegWrite_out_stage_4,
     RegWrite_in_stage_5);
  input clk, ALUSrc_stage_2, MemToReg_stage_2, RegWrite_stage_2,
       MemRead_stage_2, MemWrite_stage_2, Branch_stage_2, zero_stage_3,
       MemToReg_out_stage_3, RegWrite_out_stage_3, MemRead_out_stage_3,
       MemWrite_out_stage_3, Branch_out_stage_3, MemToReg_out_stage_4,
       RegWrite_out_stage_4;
  input [63:0] pc_out_stage_1, pc_out_stage_2, read_data1_stage_2,
       read_data2_stage_2, immediate_stage_2, sum_stage_3,
       alu_result_stage_3, read_data2_out_stage_3,
       read_data_out_stage_4, alu_result_out_stage_4;
  input [31:0] instruction_stage_1;
  input [4:0] write_register_out_stage_2, write_register_out_stage_3,
       write_register_out_stage_4;
  input [1:0] ALUOp_stage_2;
  input [3:0] ALU_control_input_stage_2;
  output [63:0] pc_in_stage_2, pc_in_stage_3, read_data1_stage_3,
       read_data2_in_stage_3, immediate_stage_3, sum_in_stage_4,
       alu_result_in_stage_4, read_data2_in_stage_4,
       read_data_in_stage_5, alu_result_in_stage_5;
  output [31:0] instruction_stage_2;
  output [4:0] write_register_in_stage_3, write_register_in_stage_4,
       write_register_in_stage_5;
  output ALUSrc_stage_3, MemToReg_in_stage_3, RegWrite_in_stage_3,
       MemRead_in_stage_3, MemWrite_in_stage_3, Branch_in_stage_3,
       zero_stage_4, MemToReg_in_stage_4, RegWrite_in_stage_4,
       MemRead_in_stage_4, MemWrite_in_stage_4, Branch_in_stage_4,
       MemToReg_in_stage_5, RegWrite_in_stage_5;
  output [1:0] ALUOp_stage_3;
  output [3:0] ALU_control_input_stage_3;
  wire clk, ALUSrc_stage_2, MemToReg_stage_2, RegWrite_stage_2,
       MemRead_stage_2, MemWrite_stage_2, Branch_stage_2, zero_stage_3,
       MemToReg_out_stage_3, RegWrite_out_stage_3, MemRead_out_stage_3,
       MemWrite_out_stage_3, Branch_out_stage_3, MemToReg_out_stage_4,
       RegWrite_out_stage_4;
  wire [63:0] pc_out_stage_1, pc_out_stage_2, read_data1_stage_2,
       read_data2_stage_2, immediate_stage_2, sum_stage_3,
       alu_result_stage_3, read_data2_out_stage_3,
       read_data_out_stage_4, alu_result_out_stage_4;
  wire [31:0] instruction_stage_1;
  wire [4:0] write_register_out_stage_2, write_register_out_stage_3,
       write_register_out_stage_4;
  wire [1:0] ALUOp_stage_2;
  wire [3:0] ALU_control_input_stage_2;
  wire [63:0] pc_in_stage_2, pc_in_stage_3, read_data1_stage_3,
       read_data2_in_stage_3, immediate_stage_3, sum_in_stage_4,
       alu_result_in_stage_4, read_data2_in_stage_4,
       read_data_in_stage_5, alu_result_in_stage_5;
  wire [31:0] instruction_stage_2;
  wire [4:0] write_register_in_stage_3, write_register_in_stage_4,
       write_register_in_stage_5;
  wire ALUSrc_stage_3, MemToReg_in_stage_3, RegWrite_in_stage_3,
       MemRead_in_stage_3, MemWrite_in_stage_3, Branch_in_stage_3,
       zero_stage_4, MemToReg_in_stage_4, RegWrite_in_stage_4,
       MemRead_in_stage_4, MemWrite_in_stage_4, Branch_in_stage_4,
       MemToReg_in_stage_5, RegWrite_in_stage_5;
  wire [1:0] ALUOp_stage_3;
  wire [3:0] ALU_control_input_stage_3;
  DFQM2RA \pc_in_stage_2_reg[63] (.CK (clk), .D (pc_out_stage_1[63]),
       .Q (pc_in_stage_2[63]));
  DFQM2RA \pc_in_stage_2_reg[62] (.CK (clk), .D (pc_out_stage_1[62]),
       .Q (pc_in_stage_2[62]));
  DFQM2RA \pc_in_stage_2_reg[60] (.CK (clk), .D (pc_out_stage_1[60]),
       .Q (pc_in_stage_2[60]));
  DFQM2RA \pc_in_stage_2_reg[56] (.CK (clk), .D (pc_out_stage_1[56]),
       .Q (pc_in_stage_2[56]));
  DFQM2RA \read_data2_in_stage_3_reg[33] (.CK (clk), .D
       (read_data2_stage_2[33]), .Q (read_data2_in_stage_3[33]));
  DFQM2RA \pc_in_stage_2_reg[48] (.CK (clk), .D (pc_out_stage_1[48]),
       .Q (pc_in_stage_2[48]));
  DFQM2RA \pc_in_stage_2_reg[32] (.CK (clk), .D (pc_out_stage_1[32]),
       .Q (pc_in_stage_2[32]));
  DFQM2RA \pc_in_stage_2_reg[0] (.CK (clk), .D (pc_out_stage_1[0]), .Q
       (pc_in_stage_2[0]));
  DFQM2RA \pc_in_stage_3_reg[32] (.CK (clk), .D (pc_out_stage_2[32]),
       .Q (pc_in_stage_3[32]));
  DFQM2RA \read_data2_in_stage_3_reg[32] (.CK (clk), .D
       (read_data2_stage_2[32]), .Q (read_data2_in_stage_3[32]));
  DFQM2RA \read_data2_in_stage_4_reg[50] (.CK (clk), .D
       (read_data2_out_stage_3[50]), .Q (read_data2_in_stage_4[50]));
  DFQM2RA \read_data2_in_stage_4_reg[49] (.CK (clk), .D
       (read_data2_out_stage_3[49]), .Q (read_data2_in_stage_4[49]));
  DFQM2RA \read_data2_in_stage_3_reg[31] (.CK (clk), .D
       (read_data2_stage_2[31]), .Q (read_data2_in_stage_3[31]));
  DFQM2RA \read_data2_in_stage_4_reg[48] (.CK (clk), .D
       (read_data2_out_stage_3[48]), .Q (read_data2_in_stage_4[48]));
  DFQM2RA \read_data2_in_stage_4_reg[47] (.CK (clk), .D
       (read_data2_out_stage_3[47]), .Q (read_data2_in_stage_4[47]));
  DFQM2RA \pc_in_stage_3_reg[31] (.CK (clk), .D (pc_out_stage_2[31]),
       .Q (pc_in_stage_3[31]));
  DFQM2RA \pc_in_stage_2_reg[1] (.CK (clk), .D (pc_out_stage_1[1]), .Q
       (pc_in_stage_2[1]));
  DFQM2RA \read_data2_in_stage_3_reg[30] (.CK (clk), .D
       (read_data2_stage_2[30]), .Q (read_data2_in_stage_3[30]));
  DFQM2RA \read_data2_in_stage_4_reg[46] (.CK (clk), .D
       (read_data2_out_stage_3[46]), .Q (read_data2_in_stage_4[46]));
  DFQM2RA \read_data2_in_stage_4_reg[45] (.CK (clk), .D
       (read_data2_out_stage_3[45]), .Q (read_data2_in_stage_4[45]));
  DFQM2RA \read_data2_in_stage_4_reg[61] (.CK (clk), .D
       (read_data2_out_stage_3[61]), .Q (read_data2_in_stage_4[61]));
  DFQM2RA \read_data2_in_stage_3_reg[29] (.CK (clk), .D
       (read_data2_stage_2[29]), .Q (read_data2_in_stage_3[29]));
  DFQM2RA \read_data2_in_stage_4_reg[44] (.CK (clk), .D
       (read_data2_out_stage_3[44]), .Q (read_data2_in_stage_4[44]));
  DFQM2RA \read_data2_in_stage_4_reg[43] (.CK (clk), .D
       (read_data2_out_stage_3[43]), .Q (read_data2_in_stage_4[43]));
  DFQM2RA \read_data2_in_stage_4_reg[63] (.CK (clk), .D
       (read_data2_out_stage_3[63]), .Q (read_data2_in_stage_4[63]));
  DFQM2RA \instruction_stage_2_reg[31] (.CK (clk), .D
       (instruction_stage_1[31]), .Q (instruction_stage_2[31]));
  DFQM2RA \pc_in_stage_3_reg[30] (.CK (clk), .D (pc_out_stage_2[30]),
       .Q (pc_in_stage_3[30]));
  DFQM2RA \read_data2_in_stage_3_reg[28] (.CK (clk), .D
       (read_data2_stage_2[28]), .Q (read_data2_in_stage_3[28]));
  DFQM2RA \read_data2_in_stage_4_reg[42] (.CK (clk), .D
       (read_data2_out_stage_3[42]), .Q (read_data2_in_stage_4[42]));
  DFQM2RA \read_data2_in_stage_4_reg[41] (.CK (clk), .D
       (read_data2_out_stage_3[41]), .Q (read_data2_in_stage_4[41]));
  DFQM2RA \read_data2_in_stage_3_reg[27] (.CK (clk), .D
       (read_data2_stage_2[27]), .Q (read_data2_in_stage_3[27]));
  DFQM2RA \read_data2_in_stage_4_reg[40] (.CK (clk), .D
       (read_data2_out_stage_3[40]), .Q (read_data2_in_stage_4[40]));
  DFQM2RA \pc_in_stage_2_reg[33] (.CK (clk), .D (pc_out_stage_1[33]),
       .Q (pc_in_stage_2[33]));
  DFQM2RA \read_data2_in_stage_4_reg[39] (.CK (clk), .D
       (read_data2_out_stage_3[39]), .Q (read_data2_in_stage_4[39]));
  DFQM2RA \pc_in_stage_3_reg[29] (.CK (clk), .D (pc_out_stage_2[29]),
       .Q (pc_in_stage_3[29]));
  DFQM2RA \read_data2_in_stage_3_reg[26] (.CK (clk), .D
       (read_data2_stage_2[26]), .Q (read_data2_in_stage_3[26]));
  DFQM2RA \alu_result_in_stage_4_reg[5] (.CK (clk), .D
       (alu_result_stage_3[5]), .Q (alu_result_in_stage_4[5]));
  DFQM2RA \read_data2_in_stage_4_reg[38] (.CK (clk), .D
       (read_data2_out_stage_3[38]), .Q (read_data2_in_stage_4[38]));
  DFQM2RA \read_data2_in_stage_4_reg[37] (.CK (clk), .D
       (read_data2_out_stage_3[37]), .Q (read_data2_in_stage_4[37]));
  DFQM2RA \read_data2_in_stage_3_reg[25] (.CK (clk), .D
       (read_data2_stage_2[25]), .Q (read_data2_in_stage_3[25]));
  DFQM2RA \alu_result_in_stage_4_reg[7] (.CK (clk), .D
       (alu_result_stage_3[7]), .Q (alu_result_in_stage_4[7]));
  DFQM2RA \read_data2_in_stage_4_reg[36] (.CK (clk), .D
       (read_data2_out_stage_3[36]), .Q (read_data2_in_stage_4[36]));
  DFQM2RA \read_data2_in_stage_4_reg[35] (.CK (clk), .D
       (read_data2_out_stage_3[35]), .Q (read_data2_in_stage_4[35]));
  DFQM2RA \pc_in_stage_2_reg[31] (.CK (clk), .D (pc_out_stage_1[31]),
       .Q (pc_in_stage_2[31]));
  DFQM2RA \instruction_stage_2_reg[30] (.CK (clk), .D
       (instruction_stage_1[30]), .Q (instruction_stage_2[30]));
  DFQM2RA \pc_in_stage_3_reg[28] (.CK (clk), .D (pc_out_stage_2[28]),
       .Q (pc_in_stage_3[28]));
  DFQM2RA \read_data2_in_stage_3_reg[24] (.CK (clk), .D
       (read_data2_stage_2[24]), .Q (read_data2_in_stage_3[24]));
  DFQM2RA \read_data2_in_stage_4_reg[34] (.CK (clk), .D
       (read_data2_out_stage_3[34]), .Q (read_data2_in_stage_4[34]));
  DFQM2RA \alu_result_in_stage_4_reg[11] (.CK (clk), .D
       (alu_result_stage_3[11]), .Q (alu_result_in_stage_4[11]));
  DFQM2RA \read_data2_in_stage_4_reg[33] (.CK (clk), .D
       (read_data2_out_stage_3[33]), .Q (read_data2_in_stage_4[33]));
  DFQM2RA \read_data2_in_stage_3_reg[23] (.CK (clk), .D
       (read_data2_stage_2[23]), .Q (read_data2_in_stage_3[23]));
  DFQM2RA \read_data2_in_stage_4_reg[32] (.CK (clk), .D
       (read_data2_out_stage_3[32]), .Q (read_data2_in_stage_4[32]));
  DFQM2RA \alu_result_in_stage_4_reg[14] (.CK (clk), .D
       (alu_result_stage_3[14]), .Q (alu_result_in_stage_4[14]));
  DFQM2RA \read_data2_in_stage_4_reg[31] (.CK (clk), .D
       (read_data2_out_stage_3[31]), .Q (read_data2_in_stage_4[31]));
  DFQM2RA \pc_in_stage_3_reg[27] (.CK (clk), .D (pc_out_stage_2[27]),
       .Q (pc_in_stage_3[27]));
  DFQM2RA \read_data2_in_stage_3_reg[22] (.CK (clk), .D
       (read_data2_stage_2[22]), .Q (read_data2_in_stage_3[22]));
  DFQM2RA \alu_result_in_stage_4_reg[16] (.CK (clk), .D
       (alu_result_stage_3[16]), .Q (alu_result_in_stage_4[16]));
  DFQM2RA \read_data2_in_stage_4_reg[30] (.CK (clk), .D
       (read_data2_out_stage_3[30]), .Q (read_data2_in_stage_4[30]));
  DFQM2RA \read_data2_in_stage_4_reg[29] (.CK (clk), .D
       (read_data2_out_stage_3[29]), .Q (read_data2_in_stage_4[29]));
  DFQM2RA \read_data2_in_stage_3_reg[21] (.CK (clk), .D
       (read_data2_stage_2[21]), .Q (read_data2_in_stage_3[21]));
  DFQM2RA \read_data2_in_stage_4_reg[28] (.CK (clk), .D
       (read_data2_out_stage_3[28]), .Q (read_data2_in_stage_4[28]));
  DFQM2RA \read_data2_in_stage_4_reg[27] (.CK (clk), .D
       (read_data2_out_stage_3[27]), .Q (read_data2_in_stage_4[27]));
  DFQM2RA \instruction_stage_2_reg[29] (.CK (clk), .D
       (instruction_stage_1[29]), .Q (instruction_stage_2[29]));
  DFQM2RA \pc_in_stage_3_reg[26] (.CK (clk), .D (pc_out_stage_2[26]),
       .Q (pc_in_stage_3[26]));
  DFQM2RA \pc_in_stage_2_reg[49] (.CK (clk), .D (pc_out_stage_1[49]),
       .Q (pc_in_stage_2[49]));
  DFQM2RA \read_data2_in_stage_3_reg[20] (.CK (clk), .D
       (read_data2_stage_2[20]), .Q (read_data2_in_stage_3[20]));
  DFQM2RA \read_data2_in_stage_4_reg[26] (.CK (clk), .D
       (read_data2_out_stage_3[26]), .Q (read_data2_in_stage_4[26]));
  DFQM2RA \read_data2_in_stage_4_reg[25] (.CK (clk), .D
       (read_data2_out_stage_3[25]), .Q (read_data2_in_stage_4[25]));
  DFQM2RA \alu_result_in_stage_4_reg[21] (.CK (clk), .D
       (alu_result_stage_3[21]), .Q (alu_result_in_stage_4[21]));
  DFQM2RA \read_data2_in_stage_3_reg[19] (.CK (clk), .D
       (read_data2_stage_2[19]), .Q (read_data2_in_stage_3[19]));
  DFQM2RA \read_data2_in_stage_4_reg[24] (.CK (clk), .D
       (read_data2_out_stage_3[24]), .Q (read_data2_in_stage_4[24]));
  DFQM2RA \read_data2_in_stage_4_reg[23] (.CK (clk), .D
       (read_data2_out_stage_3[23]), .Q (read_data2_in_stage_4[23]));
  DFQM2RA \alu_result_in_stage_4_reg[23] (.CK (clk), .D
       (alu_result_stage_3[23]), .Q (alu_result_in_stage_4[23]));
  DFQM2RA \pc_in_stage_3_reg[25] (.CK (clk), .D (pc_out_stage_2[25]),
       .Q (pc_in_stage_3[25]));
  DFQM2RA \read_data2_in_stage_3_reg[18] (.CK (clk), .D
       (read_data2_stage_2[18]), .Q (read_data2_in_stage_3[18]));
  DFQM2RA \read_data2_in_stage_4_reg[22] (.CK (clk), .D
       (read_data2_out_stage_3[22]), .Q (read_data2_in_stage_4[22]));
  DFQM2RA \read_data2_in_stage_4_reg[21] (.CK (clk), .D
       (read_data2_out_stage_3[21]), .Q (read_data2_in_stage_4[21]));
  DFQM2RA \read_data2_in_stage_3_reg[17] (.CK (clk), .D
       (read_data2_stage_2[17]), .Q (read_data2_in_stage_3[17]));
  DFQM2RA \read_data2_in_stage_4_reg[20] (.CK (clk), .D
       (read_data2_out_stage_3[20]), .Q (read_data2_in_stage_4[20]));
  DFQM2RA \read_data2_in_stage_4_reg[19] (.CK (clk), .D
       (read_data2_out_stage_3[19]), .Q (read_data2_in_stage_4[19]));
  DFQM2RA \alu_result_in_stage_4_reg[27] (.CK (clk), .D
       (alu_result_stage_3[27]), .Q (alu_result_in_stage_4[27]));
  DFQM2RA \pc_in_stage_2_reg[47] (.CK (clk), .D (pc_out_stage_1[47]),
       .Q (pc_in_stage_2[47]));
  DFQM2RA \pc_in_stage_2_reg[30] (.CK (clk), .D (pc_out_stage_1[30]),
       .Q (pc_in_stage_2[30]));
  DFQM2RA \instruction_stage_2_reg[28] (.CK (clk), .D
       (instruction_stage_1[28]), .Q (instruction_stage_2[28]));
  DFQM2RA \alu_result_in_stage_4_reg[30] (.CK (clk), .D
       (alu_result_stage_3[30]), .Q (alu_result_in_stage_4[30]));
  DFQM2RA \pc_in_stage_3_reg[24] (.CK (clk), .D (pc_out_stage_2[24]),
       .Q (pc_in_stage_3[24]));
  DFQM2RA \read_data2_in_stage_3_reg[16] (.CK (clk), .D
       (read_data2_stage_2[16]), .Q (read_data2_in_stage_3[16]));
  DFQM2RA \read_data2_in_stage_4_reg[18] (.CK (clk), .D
       (read_data2_out_stage_3[18]), .Q (read_data2_in_stage_4[18]));
  DFQM2RA \alu_result_in_stage_4_reg[32] (.CK (clk), .D
       (alu_result_stage_3[32]), .Q (alu_result_in_stage_4[32]));
  DFQM2RA \read_data2_in_stage_4_reg[17] (.CK (clk), .D
       (read_data2_out_stage_3[17]), .Q (read_data2_in_stage_4[17]));
  DFQM2RA \read_data2_in_stage_3_reg[15] (.CK (clk), .D
       (read_data2_stage_2[15]), .Q (read_data2_in_stage_3[15]));
  DFQM2RA \read_data2_in_stage_4_reg[16] (.CK (clk), .D
       (read_data2_out_stage_3[16]), .Q (read_data2_in_stage_4[16]));
  DFQM2RA \read_data2_in_stage_4_reg[15] (.CK (clk), .D
       (read_data2_out_stage_3[15]), .Q (read_data2_in_stage_4[15]));
  DFQM2RA \pc_in_stage_3_reg[23] (.CK (clk), .D (pc_out_stage_2[23]),
       .Q (pc_in_stage_3[23]));
  DFQM2RA \read_data2_in_stage_3_reg[14] (.CK (clk), .D
       (read_data2_stage_2[14]), .Q (read_data2_in_stage_3[14]));
  DFQM2RA \read_data2_in_stage_4_reg[14] (.CK (clk), .D
       (read_data2_out_stage_3[14]), .Q (read_data2_in_stage_4[14]));
  DFQM2RA \alu_result_in_stage_4_reg[35] (.CK (clk), .D
       (alu_result_stage_3[35]), .Q (alu_result_in_stage_4[35]));
  DFQM2RA \read_data2_in_stage_4_reg[13] (.CK (clk), .D
       (read_data2_out_stage_3[13]), .Q (read_data2_in_stage_4[13]));
  DFQM2RA \read_data2_in_stage_3_reg[13] (.CK (clk), .D
       (read_data2_stage_2[13]), .Q (read_data2_in_stage_3[13]));
  DFQM2RA \read_data2_in_stage_4_reg[12] (.CK (clk), .D
       (read_data2_out_stage_3[12]), .Q (read_data2_in_stage_4[12]));
  DFQM2RA \alu_result_in_stage_4_reg[38] (.CK (clk), .D
       (alu_result_stage_3[38]), .Q (alu_result_in_stage_4[38]));
  DFQM2RA \read_data2_in_stage_4_reg[11] (.CK (clk), .D
       (read_data2_out_stage_3[11]), .Q (read_data2_in_stage_4[11]));
  DFQM2RA \instruction_stage_2_reg[27] (.CK (clk), .D
       (instruction_stage_1[27]), .Q (instruction_stage_2[27]));
  DFQM2RA \pc_in_stage_3_reg[22] (.CK (clk), .D (pc_out_stage_2[22]),
       .Q (pc_in_stage_3[22]));
  DFQM2RA \alu_result_in_stage_4_reg[40] (.CK (clk), .D
       (alu_result_stage_3[40]), .Q (alu_result_in_stage_4[40]));
  DFQM2RA \read_data2_in_stage_3_reg[12] (.CK (clk), .D
       (read_data2_stage_2[12]), .Q (read_data2_in_stage_3[12]));
  DFQM2RA \read_data2_in_stage_4_reg[10] (.CK (clk), .D
       (read_data2_out_stage_3[10]), .Q (read_data2_in_stage_4[10]));
  DFQM2RA \read_data2_in_stage_4_reg[9] (.CK (clk), .D
       (read_data2_out_stage_3[9]), .Q (read_data2_in_stage_4[9]));
  DFQM2RA \read_data2_in_stage_3_reg[11] (.CK (clk), .D
       (read_data2_stage_2[11]), .Q (read_data2_in_stage_3[11]));
  DFQM2RA \read_data2_in_stage_4_reg[8] (.CK (clk), .D
       (read_data2_out_stage_3[8]), .Q (read_data2_in_stage_4[8]));
  DFQM2RA \read_data2_in_stage_4_reg[7] (.CK (clk), .D
       (read_data2_out_stage_3[7]), .Q (read_data2_in_stage_4[7]));
  DFQM2RA \pc_in_stage_3_reg[21] (.CK (clk), .D (pc_out_stage_2[21]),
       .Q (pc_in_stage_3[21]));
  DFQM2RA \alu_result_in_stage_4_reg[44] (.CK (clk), .D
       (alu_result_stage_3[44]), .Q (alu_result_in_stage_4[44]));
  DFQM2RA \read_data2_in_stage_3_reg[10] (.CK (clk), .D
       (read_data2_stage_2[10]), .Q (read_data2_in_stage_3[10]));
  DFQM2RA \read_data2_in_stage_4_reg[6] (.CK (clk), .D
       (read_data2_out_stage_3[6]), .Q (read_data2_in_stage_4[6]));
  DFQM2RA \read_data2_in_stage_4_reg[5] (.CK (clk), .D
       (read_data2_out_stage_3[5]), .Q (read_data2_in_stage_4[5]));
  DFQM2RA \read_data2_in_stage_3_reg[62] (.CK (clk), .D
       (read_data2_stage_2[62]), .Q (read_data2_in_stage_3[62]));
  DFQM2RA \read_data2_in_stage_3_reg[9] (.CK (clk), .D
       (read_data2_stage_2[9]), .Q (read_data2_in_stage_3[9]));
  DFQM2RA \read_data2_in_stage_4_reg[4] (.CK (clk), .D
       (read_data2_out_stage_3[4]), .Q (read_data2_in_stage_4[4]));
  DFQM2RA \read_data2_in_stage_4_reg[3] (.CK (clk), .D
       (read_data2_out_stage_3[3]), .Q (read_data2_in_stage_4[3]));
  DFQM2RA \read_data2_in_stage_3_reg[63] (.CK (clk), .D
       (read_data2_stage_2[63]), .Q (read_data2_in_stage_3[63]));
  DFQM2RA \pc_in_stage_2_reg[29] (.CK (clk), .D (pc_out_stage_1[29]),
       .Q (pc_in_stage_2[29]));
  DFQM2RA \instruction_stage_2_reg[26] (.CK (clk), .D
       (instruction_stage_1[26]), .Q (instruction_stage_2[26]));
  DFQM2RA \pc_in_stage_3_reg[20] (.CK (clk), .D (pc_out_stage_2[20]),
       .Q (pc_in_stage_3[20]));
  DFQM2RA \read_data2_in_stage_3_reg[8] (.CK (clk), .D
       (read_data2_stage_2[8]), .Q (read_data2_in_stage_3[8]));
  DFQM2RA \read_data2_in_stage_4_reg[2] (.CK (clk), .D
       (read_data2_out_stage_3[2]), .Q (read_data2_in_stage_4[2]));
  DFQM2RA \read_data2_in_stage_4_reg[1] (.CK (clk), .D
       (read_data2_out_stage_3[1]), .Q (read_data2_in_stage_4[1]));
  DFQM2RA \read_data2_in_stage_3_reg[7] (.CK (clk), .D
       (read_data2_stage_2[7]), .Q (read_data2_in_stage_3[7]));
  DFQM2RA \pc_in_stage_2_reg[57] (.CK (clk), .D (pc_out_stage_1[57]),
       .Q (pc_in_stage_2[57]));
  DFQM2RA \read_data2_in_stage_4_reg[0] (.CK (clk), .D
       (read_data2_out_stage_3[0]), .Q (read_data2_in_stage_4[0]));
  DFQM2RA \write_register_in_stage_4_reg[4] (.CK (clk), .D
       (write_register_out_stage_3[4]), .Q
       (write_register_in_stage_4[4]));
  DFQM2RA \pc_in_stage_3_reg[19] (.CK (clk), .D (pc_out_stage_2[19]),
       .Q (pc_in_stage_3[19]));
  DFQM2RA \alu_result_in_stage_4_reg[53] (.CK (clk), .D
       (alu_result_stage_3[53]), .Q (alu_result_in_stage_4[53]));
  DFQM2RA \read_data2_in_stage_3_reg[6] (.CK (clk), .D
       (read_data2_stage_2[6]), .Q (read_data2_in_stage_3[6]));
  DFQM2RA \write_register_in_stage_4_reg[3] (.CK (clk), .D
       (write_register_out_stage_3[3]), .Q
       (write_register_in_stage_4[3]));
  DFQM2RA \write_register_in_stage_4_reg[2] (.CK (clk), .D
       (write_register_out_stage_3[2]), .Q
       (write_register_in_stage_4[2]));
  DFQM2RA \alu_result_in_stage_4_reg[55] (.CK (clk), .D
       (alu_result_stage_3[55]), .Q (alu_result_in_stage_4[55]));
  DFQM2RA \read_data2_in_stage_3_reg[5] (.CK (clk), .D
       (read_data2_stage_2[5]), .Q (read_data2_in_stage_3[5]));
  DFQM2RA \write_register_in_stage_4_reg[1] (.CK (clk), .D
       (write_register_out_stage_3[1]), .Q
       (write_register_in_stage_4[1]));
  DFQM2RA \write_register_in_stage_4_reg[0] (.CK (clk), .D
       (write_register_out_stage_3[0]), .Q
       (write_register_in_stage_4[0]));
  DFQM2RA \instruction_stage_2_reg[25] (.CK (clk), .D
       (instruction_stage_1[25]), .Q (instruction_stage_2[25]));
  DFQM2RA \pc_in_stage_3_reg[18] (.CK (clk), .D (pc_out_stage_2[18]),
       .Q (pc_in_stage_3[18]));
  DFQM2RA \read_data2_in_stage_3_reg[4] (.CK (clk), .D
       (read_data2_stage_2[4]), .Q (read_data2_in_stage_3[4]));
  DFQM2RA MemToReg_in_stage_4_reg(.CK (clk), .D (MemToReg_out_stage_3),
       .Q (MemToReg_in_stage_4));
  DFQM2RA \alu_result_in_stage_4_reg[59] (.CK (clk), .D
       (alu_result_stage_3[59]), .Q (alu_result_in_stage_4[59]));
  DFQM2RA RegWrite_in_stage_4_reg(.CK (clk), .D (RegWrite_out_stage_3),
       .Q (RegWrite_in_stage_4));
  DFQM2RA \read_data2_in_stage_3_reg[3] (.CK (clk), .D
       (read_data2_stage_2[3]), .Q (read_data2_in_stage_3[3]));
  DFQM2RA MemRead_in_stage_4_reg(.CK (clk), .D (MemRead_out_stage_3),
       .Q (MemRead_in_stage_4));
  DFQM2RA \alu_result_in_stage_4_reg[62] (.CK (clk), .D
       (alu_result_stage_3[62]), .Q (alu_result_in_stage_4[62]));
  DFQM2RA MemWrite_in_stage_4_reg(.CK (clk), .D (MemWrite_out_stage_3),
       .Q (MemWrite_in_stage_4));
  DFQM2RA \pc_in_stage_3_reg[17] (.CK (clk), .D (pc_out_stage_2[17]),
       .Q (pc_in_stage_3[17]));
  DFQM2RA \read_data2_in_stage_3_reg[2] (.CK (clk), .D
       (read_data2_stage_2[2]), .Q (read_data2_in_stage_3[2]));
  DFQM2RA zero_stage_4_reg(.CK (clk), .D (zero_stage_3), .Q
       (zero_stage_4));
  DFQM2RA Branch_in_stage_4_reg(.CK (clk), .D (Branch_out_stage_3), .Q
       (Branch_in_stage_4));
  DFQM2RA \read_data_in_stage_5_reg[63] (.CK (clk), .D
       (read_data_out_stage_4[63]), .Q (read_data_in_stage_5[63]));
  DFQM2RA \read_data2_in_stage_3_reg[1] (.CK (clk), .D
       (read_data2_stage_2[1]), .Q (read_data2_in_stage_3[1]));
  DFQM2RA \read_data_in_stage_5_reg[62] (.CK (clk), .D
       (read_data_out_stage_4[62]), .Q (read_data_in_stage_5[62]));
  DFQM2RA \read_data_in_stage_5_reg[61] (.CK (clk), .D
       (read_data_out_stage_4[61]), .Q (read_data_in_stage_5[61]));
  DFQM2RA \pc_in_stage_2_reg[55] (.CK (clk), .D (pc_out_stage_1[55]),
       .Q (pc_in_stage_2[55]));
  DFQM2RA \pc_in_stage_2_reg[46] (.CK (clk), .D (pc_out_stage_1[46]),
       .Q (pc_in_stage_2[46]));
  DFQM2RA \sum_in_stage_4_reg[2] (.CK (clk), .D (sum_stage_3[2]), .Q
       (sum_in_stage_4[2]));
  DFQM2RA \pc_in_stage_2_reg[28] (.CK (clk), .D (pc_out_stage_1[28]),
       .Q (pc_in_stage_2[28]));
  DFQM2RA \instruction_stage_2_reg[24] (.CK (clk), .D
       (instruction_stage_1[24]), .Q (instruction_stage_2[24]));
  DFQM2RA \pc_in_stage_3_reg[16] (.CK (clk), .D (pc_out_stage_2[16]),
       .Q (pc_in_stage_3[16]));
  DFQM2RA \sum_in_stage_4_reg[5] (.CK (clk), .D (sum_stage_3[5]), .Q
       (sum_in_stage_4[5]));
  DFQM2RA \read_data2_in_stage_3_reg[0] (.CK (clk), .D
       (read_data2_stage_2[0]), .Q (read_data2_in_stage_3[0]));
  DFQM2RA \read_data_in_stage_5_reg[60] (.CK (clk), .D
       (read_data_out_stage_4[60]), .Q (read_data_in_stage_5[60]));
  DFQM2RA \read_data_in_stage_5_reg[59] (.CK (clk), .D
       (read_data_out_stage_4[59]), .Q (read_data_in_stage_5[59]));
  DFQM2RA \sum_in_stage_4_reg[7] (.CK (clk), .D (sum_stage_3[7]), .Q
       (sum_in_stage_4[7]));
  DFQM2RA \write_register_in_stage_3_reg[4] (.CK (clk), .D
       (write_register_out_stage_2[4]), .Q
       (write_register_in_stage_3[4]));
  DFQM2RA \read_data_in_stage_5_reg[58] (.CK (clk), .D
       (read_data_out_stage_4[58]), .Q (read_data_in_stage_5[58]));
  DFQM2RA \read_data_in_stage_5_reg[57] (.CK (clk), .D
       (read_data_out_stage_4[57]), .Q (read_data_in_stage_5[57]));
  DFQM2RA \pc_in_stage_3_reg[15] (.CK (clk), .D (pc_out_stage_2[15]),
       .Q (pc_in_stage_3[15]));
  DFQM2RA \write_register_in_stage_3_reg[3] (.CK (clk), .D
       (write_register_out_stage_2[3]), .Q
       (write_register_in_stage_3[3]));
  DFQM2RA \read_data_in_stage_5_reg[56] (.CK (clk), .D
       (read_data_out_stage_4[56]), .Q (read_data_in_stage_5[56]));
  DFQM2RA \read_data_in_stage_5_reg[55] (.CK (clk), .D
       (read_data_out_stage_4[55]), .Q (read_data_in_stage_5[55]));
  DFQM2RA \sum_in_stage_4_reg[11] (.CK (clk), .D (sum_stage_3[11]), .Q
       (sum_in_stage_4[11]));
  DFQM2RA \write_register_in_stage_3_reg[2] (.CK (clk), .D
       (write_register_out_stage_2[2]), .Q
       (write_register_in_stage_3[2]));
  DFQM2RA \read_data_in_stage_5_reg[54] (.CK (clk), .D
       (read_data_out_stage_4[54]), .Q (read_data_in_stage_5[54]));
  DFQM2RA \read_data_in_stage_5_reg[53] (.CK (clk), .D
       (read_data_out_stage_4[53]), .Q (read_data_in_stage_5[53]));
  DFQM2RA \read_data1_stage_3_reg[14] (.CK (clk), .D
       (read_data1_stage_2[14]), .Q (read_data1_stage_3[14]));
  DFQM2RA \instruction_stage_2_reg[23] (.CK (clk), .D
       (instruction_stage_1[23]), .Q (instruction_stage_2[23]));
  DFQM2RA \pc_in_stage_3_reg[14] (.CK (clk), .D (pc_out_stage_2[14]),
       .Q (pc_in_stage_3[14]));
  DFQM2RA \write_register_in_stage_3_reg[1] (.CK (clk), .D
       (write_register_out_stage_2[1]), .Q
       (write_register_in_stage_3[1]));
  DFQM2RA \read_data1_stage_3_reg[15] (.CK (clk), .D
       (read_data1_stage_2[15]), .Q (read_data1_stage_3[15]));
  DFQM2RA \read_data_in_stage_5_reg[52] (.CK (clk), .D
       (read_data_out_stage_4[52]), .Q (read_data_in_stage_5[52]));
  DFQM2RA \read_data_in_stage_5_reg[51] (.CK (clk), .D
       (read_data_out_stage_4[51]), .Q (read_data_in_stage_5[51]));
  DFQM2RA \write_register_in_stage_3_reg[0] (.CK (clk), .D
       (write_register_out_stage_2[0]), .Q
       (write_register_in_stage_3[0]));
  DFQM2RA \read_data_in_stage_5_reg[50] (.CK (clk), .D
       (read_data_out_stage_4[50]), .Q (read_data_in_stage_5[50]));
  DFQM2RA \read_data_in_stage_5_reg[49] (.CK (clk), .D
       (read_data_out_stage_4[49]), .Q (read_data_in_stage_5[49]));
  DFQM2RA \pc_in_stage_3_reg[13] (.CK (clk), .D (pc_out_stage_2[13]),
       .Q (pc_in_stage_3[13]));
  DFQM2RA ALUSrc_stage_3_reg(.CK (clk), .D (ALUSrc_stage_2), .Q
       (ALUSrc_stage_3));
  DFQM2RA \sum_in_stage_4_reg[18] (.CK (clk), .D (sum_stage_3[18]), .Q
       (sum_in_stage_4[18]));
  DFQM2RA \read_data_in_stage_5_reg[48] (.CK (clk), .D
       (read_data_out_stage_4[48]), .Q (read_data_in_stage_5[48]));
  DFQM2RA \read_data_in_stage_5_reg[47] (.CK (clk), .D
       (read_data_out_stage_4[47]), .Q (read_data_in_stage_5[47]));
  DFQM2RA MemToReg_in_stage_3_reg(.CK (clk), .D (MemToReg_stage_2), .Q
       (MemToReg_in_stage_3));
  DFQM2RA \sum_in_stage_4_reg[21] (.CK (clk), .D (sum_stage_3[21]), .Q
       (sum_in_stage_4[21]));
  DFQM2RA \read_data_in_stage_5_reg[46] (.CK (clk), .D
       (read_data_out_stage_4[46]), .Q (read_data_in_stage_5[46]));
  DFQM2RA \read_data_in_stage_5_reg[45] (.CK (clk), .D
       (read_data_out_stage_4[45]), .Q (read_data_in_stage_5[45]));
  DFQM2RA \pc_in_stage_2_reg[27] (.CK (clk), .D (pc_out_stage_1[27]),
       .Q (pc_in_stage_2[27]));
  DFQM2RA \sum_in_stage_4_reg[23] (.CK (clk), .D (sum_stage_3[23]), .Q
       (sum_in_stage_4[23]));
  DFQM2RA \instruction_stage_2_reg[22] (.CK (clk), .D
       (instruction_stage_1[22]), .Q (instruction_stage_2[22]));
  DFQM2RA \pc_in_stage_3_reg[12] (.CK (clk), .D (pc_out_stage_2[12]),
       .Q (pc_in_stage_3[12]));
  DFQM2RA RegWrite_in_stage_3_reg(.CK (clk), .D (RegWrite_stage_2), .Q
       (RegWrite_in_stage_3));
  DFQM2RA \read_data_in_stage_5_reg[44] (.CK (clk), .D
       (read_data_out_stage_4[44]), .Q (read_data_in_stage_5[44]));
  DFQM2RA \read_data_in_stage_5_reg[43] (.CK (clk), .D
       (read_data_out_stage_4[43]), .Q (read_data_in_stage_5[43]));
  DFQM2RA MemRead_in_stage_3_reg(.CK (clk), .D (MemRead_stage_2), .Q
       (MemRead_in_stage_3));
  DFQM2RA \read_data_in_stage_5_reg[42] (.CK (clk), .D
       (read_data_out_stage_4[42]), .Q (read_data_in_stage_5[42]));
  DFQM2RA \sum_in_stage_4_reg[27] (.CK (clk), .D (sum_stage_3[27]), .Q
       (sum_in_stage_4[27]));
  DFQM2RA \read_data_in_stage_5_reg[41] (.CK (clk), .D
       (read_data_out_stage_4[41]), .Q (read_data_in_stage_5[41]));
  DFQM2RA \pc_in_stage_3_reg[11] (.CK (clk), .D (pc_out_stage_2[11]),
       .Q (pc_in_stage_3[11]));
  DFQM2RA MemWrite_in_stage_3_reg(.CK (clk), .D (MemWrite_stage_2), .Q
       (MemWrite_in_stage_3));
  DFQM2RA \read_data1_stage_3_reg[22] (.CK (clk), .D
       (read_data1_stage_2[22]), .Q (read_data1_stage_3[22]));
  DFQM2RA \read_data_in_stage_5_reg[40] (.CK (clk), .D
       (read_data_out_stage_4[40]), .Q (read_data_in_stage_5[40]));
  DFQM2RA \read_data_in_stage_5_reg[39] (.CK (clk), .D
       (read_data_out_stage_4[39]), .Q (read_data_in_stage_5[39]));
  DFQM2RA Branch_in_stage_3_reg(.CK (clk), .D (Branch_stage_2), .Q
       (Branch_in_stage_3));
  DFQM2RA \read_data1_stage_3_reg[23] (.CK (clk), .D
       (read_data1_stage_2[23]), .Q (read_data1_stage_3[23]));
  DFQM2RA \read_data_in_stage_5_reg[38] (.CK (clk), .D
       (read_data_out_stage_4[38]), .Q (read_data_in_stage_5[38]));
  DFQM2RA \read_data_in_stage_5_reg[37] (.CK (clk), .D
       (read_data_out_stage_4[37]), .Q (read_data_in_stage_5[37]));
  DFQM2RA \instruction_stage_2_reg[21] (.CK (clk), .D
       (instruction_stage_1[21]), .Q (instruction_stage_2[21]));
  DFQM2RA \pc_in_stage_3_reg[10] (.CK (clk), .D (pc_out_stage_2[10]),
       .Q (pc_in_stage_3[10]));
  DFQM2RA \ALUOp_stage_3_reg[1] (.CK (clk), .D (ALUOp_stage_2[1]), .Q
       (ALUOp_stage_3[1]));
  DFQM2RA \read_data_in_stage_5_reg[36] (.CK (clk), .D
       (read_data_out_stage_4[36]), .Q (read_data_in_stage_5[36]));
  DFQM2RA \read_data_in_stage_5_reg[35] (.CK (clk), .D
       (read_data_out_stage_4[35]), .Q (read_data_in_stage_5[35]));
  DFQM2RA \sum_in_stage_4_reg[35] (.CK (clk), .D (sum_stage_3[35]), .Q
       (sum_in_stage_4[35]));
  DFQM2RA \ALUOp_stage_3_reg[0] (.CK (clk), .D (ALUOp_stage_2[0]), .Q
       (ALUOp_stage_3[0]));
  DFQM2RA \read_data_in_stage_5_reg[34] (.CK (clk), .D
       (read_data_out_stage_4[34]), .Q (read_data_in_stage_5[34]));
  DFQM2RA \read_data_in_stage_5_reg[33] (.CK (clk), .D
       (read_data_out_stage_4[33]), .Q (read_data_in_stage_5[33]));
  DFQM2RA \read_data1_stage_3_reg[26] (.CK (clk), .D
       (read_data1_stage_2[26]), .Q (read_data1_stage_3[26]));
  DFQM2RA \pc_in_stage_3_reg[9] (.CK (clk), .D (pc_out_stage_2[9]), .Q
       (pc_in_stage_3[9]));
  DFQM2RA \immediate_stage_3_reg[63] (.CK (clk), .D
       (immediate_stage_2[63]), .Q (immediate_stage_3[63]));
  DFQM2RA \read_data_in_stage_5_reg[32] (.CK (clk), .D
       (read_data_out_stage_4[32]), .Q (read_data_in_stage_5[32]));
  DFQM2RA \read_data1_stage_3_reg[27] (.CK (clk), .D
       (read_data1_stage_2[27]), .Q (read_data1_stage_3[27]));
  DFQM2RA \read_data_in_stage_5_reg[31] (.CK (clk), .D
       (read_data_out_stage_4[31]), .Q (read_data_in_stage_5[31]));
  DFQM2RA \immediate_stage_3_reg[62] (.CK (clk), .D
       (immediate_stage_2[62]), .Q (immediate_stage_3[62]));
  DFQM2RA \read_data_in_stage_5_reg[30] (.CK (clk), .D
       (read_data_out_stage_4[30]), .Q (read_data_in_stage_5[30]));
  DFQM2RA \read_data_in_stage_5_reg[29] (.CK (clk), .D
       (read_data_out_stage_4[29]), .Q (read_data_in_stage_5[29]));
  DFQM2RA \pc_in_stage_2_reg[45] (.CK (clk), .D (pc_out_stage_1[45]),
       .Q (pc_in_stage_2[45]));
  DFQM2RA \pc_in_stage_2_reg[26] (.CK (clk), .D (pc_out_stage_1[26]),
       .Q (pc_in_stage_2[26]));
  DFQM2RA \instruction_stage_2_reg[20] (.CK (clk), .D
       (instruction_stage_1[20]), .Q (instruction_stage_2[20]));
  DFQM2RA \read_data1_stage_3_reg[29] (.CK (clk), .D
       (read_data1_stage_2[29]), .Q (read_data1_stage_3[29]));
  DFQM2RA \pc_in_stage_3_reg[8] (.CK (clk), .D (pc_out_stage_2[8]), .Q
       (pc_in_stage_3[8]));
  DFQM2RA \immediate_stage_3_reg[61] (.CK (clk), .D
       (immediate_stage_2[61]), .Q (immediate_stage_3[61]));
  DFQM2RA \read_data_in_stage_5_reg[28] (.CK (clk), .D
       (read_data_out_stage_4[28]), .Q (read_data_in_stage_5[28]));
  DFQM2RA \pc_in_stage_3_reg[63] (.CK (clk), .D (pc_out_stage_2[63]),
       .Q (pc_in_stage_3[63]));
  DFQM2RA \read_data_in_stage_5_reg[27] (.CK (clk), .D
       (read_data_out_stage_4[27]), .Q (read_data_in_stage_5[27]));
  DFQM2RA \immediate_stage_3_reg[60] (.CK (clk), .D
       (immediate_stage_2[60]), .Q (immediate_stage_3[60]));
  DFQM2RA \read_data_in_stage_5_reg[26] (.CK (clk), .D
       (read_data_out_stage_4[26]), .Q (read_data_in_stage_5[26]));
  DFQM2RA \sum_in_stage_4_reg[48] (.CK (clk), .D (sum_stage_3[48]), .Q
       (sum_in_stage_4[48]));
  DFQM2RA \read_data_in_stage_5_reg[25] (.CK (clk), .D
       (read_data_out_stage_4[25]), .Q (read_data_in_stage_5[25]));
  DFQM2RA \pc_in_stage_3_reg[7] (.CK (clk), .D (pc_out_stage_2[7]), .Q
       (pc_in_stage_3[7]));
  DFQM2RA \immediate_stage_3_reg[59] (.CK (clk), .D
       (immediate_stage_2[59]), .Q (immediate_stage_3[59]));
  DFQM2RA \read_data_in_stage_5_reg[24] (.CK (clk), .D
       (read_data_out_stage_4[24]), .Q (read_data_in_stage_5[24]));
  DFQM2RA \read_data_in_stage_5_reg[23] (.CK (clk), .D
       (read_data_out_stage_4[23]), .Q (read_data_in_stage_5[23]));
  DFQM2RA \immediate_stage_3_reg[58] (.CK (clk), .D
       (immediate_stage_2[58]), .Q (immediate_stage_3[58]));
  DFQM2RA \read_data_in_stage_5_reg[22] (.CK (clk), .D
       (read_data_out_stage_4[22]), .Q (read_data_in_stage_5[22]));
  DFQM2RA \pc_in_stage_2_reg[61] (.CK (clk), .D (pc_out_stage_1[61]),
       .Q (pc_in_stage_2[61]));
  DFQM2RA \read_data_in_stage_5_reg[21] (.CK (clk), .D
       (read_data_out_stage_4[21]), .Q (read_data_in_stage_5[21]));
  DFQM2RA \instruction_stage_2_reg[19] (.CK (clk), .D
       (instruction_stage_1[19]), .Q (instruction_stage_2[19]));
  DFQM2RA \pc_in_stage_3_reg[6] (.CK (clk), .D (pc_out_stage_2[6]), .Q
       (pc_in_stage_3[6]));
  DFQM2RA \sum_in_stage_4_reg[52] (.CK (clk), .D (sum_stage_3[52]), .Q
       (sum_in_stage_4[52]));
  DFQM2RA \immediate_stage_3_reg[57] (.CK (clk), .D
       (immediate_stage_2[57]), .Q (immediate_stage_3[57]));
  DFQM2RA \read_data_in_stage_5_reg[20] (.CK (clk), .D
       (read_data_out_stage_4[20]), .Q (read_data_in_stage_5[20]));
  DFQM2RA \read_data_in_stage_5_reg[19] (.CK (clk), .D
       (read_data_out_stage_4[19]), .Q (read_data_in_stage_5[19]));
  DFQM2RA \immediate_stage_3_reg[56] (.CK (clk), .D
       (immediate_stage_2[56]), .Q (immediate_stage_3[56]));
  DFQM2RA \read_data_in_stage_5_reg[18] (.CK (clk), .D
       (read_data_out_stage_4[18]), .Q (read_data_in_stage_5[18]));
  DFQM2RA \read_data_in_stage_5_reg[17] (.CK (clk), .D
       (read_data_out_stage_4[17]), .Q (read_data_in_stage_5[17]));
  DFQM2RA \pc_in_stage_3_reg[5] (.CK (clk), .D (pc_out_stage_2[5]), .Q
       (pc_in_stage_3[5]));
  DFQM2RA \immediate_stage_3_reg[55] (.CK (clk), .D
       (immediate_stage_2[55]), .Q (immediate_stage_3[55]));
  DFQM2RA \read_data_in_stage_5_reg[16] (.CK (clk), .D
       (read_data_out_stage_4[16]), .Q (read_data_in_stage_5[16]));
  DFQM2RA \read_data_in_stage_5_reg[15] (.CK (clk), .D
       (read_data_out_stage_4[15]), .Q (read_data_in_stage_5[15]));
  DFQM2RA \immediate_stage_3_reg[54] (.CK (clk), .D
       (immediate_stage_2[54]), .Q (immediate_stage_3[54]));
  DFQM2RA \sum_in_stage_4_reg[58] (.CK (clk), .D (sum_stage_3[58]), .Q
       (sum_in_stage_4[58]));
  DFQM2RA \read_data_in_stage_5_reg[14] (.CK (clk), .D
       (read_data_out_stage_4[14]), .Q (read_data_in_stage_5[14]));
  DFQM2RA \read_data_in_stage_5_reg[13] (.CK (clk), .D
       (read_data_out_stage_4[13]), .Q (read_data_in_stage_5[13]));
  DFQM2RA \pc_in_stage_2_reg[25] (.CK (clk), .D (pc_out_stage_1[25]),
       .Q (pc_in_stage_2[25]));
  DFQM2RA \sum_in_stage_4_reg[61] (.CK (clk), .D (sum_stage_3[61]), .Q
       (sum_in_stage_4[61]));
  DFQM2RA \instruction_stage_2_reg[18] (.CK (clk), .D
       (instruction_stage_1[18]), .Q (instruction_stage_2[18]));
  DFQM2RA \pc_in_stage_3_reg[4] (.CK (clk), .D (pc_out_stage_2[4]), .Q
       (pc_in_stage_3[4]));
  DFQM2RA \immediate_stage_3_reg[53] (.CK (clk), .D
       (immediate_stage_2[53]), .Q (immediate_stage_3[53]));
  DFQM2RA \sum_in_stage_4_reg[63] (.CK (clk), .D (sum_stage_3[63]), .Q
       (sum_in_stage_4[63]));
  DFQM2RA \read_data_in_stage_5_reg[12] (.CK (clk), .D
       (read_data_out_stage_4[12]), .Q (read_data_in_stage_5[12]));
  DFQM2RA \read_data_in_stage_5_reg[11] (.CK (clk), .D
       (read_data_out_stage_4[11]), .Q (read_data_in_stage_5[11]));
  DFQM2RA \immediate_stage_3_reg[52] (.CK (clk), .D
       (immediate_stage_2[52]), .Q (immediate_stage_3[52]));
  DFQM2RA \read_data_in_stage_5_reg[10] (.CK (clk), .D
       (read_data_out_stage_4[10]), .Q (read_data_in_stage_5[10]));
  DFQM2RA \read_data_in_stage_5_reg[9] (.CK (clk), .D
       (read_data_out_stage_4[9]), .Q (read_data_in_stage_5[9]));
  DFQM2RA \pc_in_stage_3_reg[3] (.CK (clk), .D (pc_out_stage_2[3]), .Q
       (pc_in_stage_3[3]));
  DFQM2RA \immediate_stage_3_reg[51] (.CK (clk), .D
       (immediate_stage_2[51]), .Q (immediate_stage_3[51]));
  DFQM2RA \ALU_control_input_stage_3_reg[2] (.CK (clk), .D
       (ALU_control_input_stage_2[2]), .Q
       (ALU_control_input_stage_3[2]));
  DFQM2RA \read_data_in_stage_5_reg[8] (.CK (clk), .D
       (read_data_out_stage_4[8]), .Q (read_data_in_stage_5[8]));
  DFQM2RA \read_data_in_stage_5_reg[7] (.CK (clk), .D
       (read_data_out_stage_4[7]), .Q (read_data_in_stage_5[7]));
  DFQM2RA \immediate_stage_3_reg[50] (.CK (clk), .D
       (immediate_stage_2[50]), .Q (immediate_stage_3[50]));
  DFQM2RA \immediate_stage_3_reg[1] (.CK (clk), .D
       (immediate_stage_2[1]), .Q (immediate_stage_3[1]));
  DFQM2RA \read_data_in_stage_5_reg[6] (.CK (clk), .D
       (read_data_out_stage_4[6]), .Q (read_data_in_stage_5[6]));
  DFQM2RA \read_data_in_stage_5_reg[5] (.CK (clk), .D
       (read_data_out_stage_4[5]), .Q (read_data_in_stage_5[5]));
  DFQM2RA \instruction_stage_2_reg[17] (.CK (clk), .D
       (instruction_stage_1[17]), .Q (instruction_stage_2[17]));
  DFQM2RA \immediate_stage_3_reg[3] (.CK (clk), .D
       (immediate_stage_2[3]), .Q (immediate_stage_3[3]));
  DFQM2RA \pc_in_stage_3_reg[2] (.CK (clk), .D (pc_out_stage_2[2]), .Q
       (pc_in_stage_3[2]));
  DFQM2RA \immediate_stage_3_reg[49] (.CK (clk), .D
       (immediate_stage_2[49]), .Q (immediate_stage_3[49]));
  DFQM2RA \read_data_in_stage_5_reg[4] (.CK (clk), .D
       (read_data_out_stage_4[4]), .Q (read_data_in_stage_5[4]));
  DFQM2RA \read_data_in_stage_5_reg[3] (.CK (clk), .D
       (read_data_out_stage_4[3]), .Q (read_data_in_stage_5[3]));
  DFQM2RA \immediate_stage_3_reg[48] (.CK (clk), .D
       (immediate_stage_2[48]), .Q (immediate_stage_3[48]));
  DFQM2RA \read_data_in_stage_5_reg[2] (.CK (clk), .D
       (read_data_out_stage_4[2]), .Q (read_data_in_stage_5[2]));
  DFQM2RA \read_data_in_stage_5_reg[1] (.CK (clk), .D
       (read_data_out_stage_4[1]), .Q (read_data_in_stage_5[1]));
  DFQM2RA \immediate_stage_3_reg[7] (.CK (clk), .D
       (immediate_stage_2[7]), .Q (immediate_stage_3[7]));
  DFQM2RA \pc_in_stage_3_reg[1] (.CK (clk), .D (pc_out_stage_2[1]), .Q
       (pc_in_stage_3[1]));
  DFQM2RA \immediate_stage_3_reg[47] (.CK (clk), .D
       (immediate_stage_2[47]), .Q (immediate_stage_3[47]));
  DFQM2RA \read_data_in_stage_5_reg[0] (.CK (clk), .D
       (read_data_out_stage_4[0]), .Q (read_data_in_stage_5[0]));
  DFQM2RA \read_data1_stage_3_reg[46] (.CK (clk), .D
       (read_data1_stage_2[46]), .Q (read_data1_stage_3[46]));
  DFQM2RA \write_register_in_stage_5_reg[4] (.CK (clk), .D
       (write_register_out_stage_4[4]), .Q
       (write_register_in_stage_5[4]));
  DFQM2RA \immediate_stage_3_reg[46] (.CK (clk), .D
       (immediate_stage_2[46]), .Q (immediate_stage_3[46]));
  DFQM2RA \write_register_in_stage_5_reg[3] (.CK (clk), .D
       (write_register_out_stage_4[3]), .Q
       (write_register_in_stage_5[3]));
  DFQM2RA \read_data1_stage_3_reg[47] (.CK (clk), .D
       (read_data1_stage_2[47]), .Q (read_data1_stage_3[47]));
  DFQM2RA \write_register_in_stage_5_reg[2] (.CK (clk), .D
       (write_register_out_stage_4[2]), .Q
       (write_register_in_stage_5[2]));
  DFQM2RA \pc_in_stage_2_reg[59] (.CK (clk), .D (pc_out_stage_1[59]),
       .Q (pc_in_stage_2[59]));
  DFQM2RA \pc_in_stage_2_reg[54] (.CK (clk), .D (pc_out_stage_1[54]),
       .Q (pc_in_stage_2[54]));
  DFQM2RA \pc_in_stage_2_reg[44] (.CK (clk), .D (pc_out_stage_1[44]),
       .Q (pc_in_stage_2[44]));
  DFQM2RA \pc_in_stage_2_reg[24] (.CK (clk), .D (pc_out_stage_1[24]),
       .Q (pc_in_stage_2[24]));
  DFQM2RA \instruction_stage_2_reg[16] (.CK (clk), .D
       (instruction_stage_1[16]), .Q (instruction_stage_2[16]));
  DFQM2RA \pc_in_stage_3_reg[0] (.CK (clk), .D (pc_out_stage_2[0]), .Q
       (pc_in_stage_3[0]));
  DFQM2RA \instruction_stage_2_reg[8] (.CK (clk), .D
       (instruction_stage_1[8]), .Q (instruction_stage_2[8]));
  DFQM2RA \immediate_stage_3_reg[45] (.CK (clk), .D
       (immediate_stage_2[45]), .Q (immediate_stage_3[45]));
  DFQM2RA \write_register_in_stage_5_reg[1] (.CK (clk), .D
       (write_register_out_stage_4[1]), .Q
       (write_register_in_stage_5[1]));
  DFQM2RA \write_register_in_stage_5_reg[0] (.CK (clk), .D
       (write_register_out_stage_4[0]), .Q
       (write_register_in_stage_5[0]));
  DFQM2RA \alu_result_in_stage_5_reg[2] (.CK (clk), .D
       (alu_result_out_stage_4[2]), .Q (alu_result_in_stage_5[2]));
  DFQM2RA \immediate_stage_3_reg[44] (.CK (clk), .D
       (immediate_stage_2[44]), .Q (immediate_stage_3[44]));
  DFQM2RA \alu_result_in_stage_5_reg[63] (.CK (clk), .D
       (alu_result_out_stage_4[63]), .Q (alu_result_in_stage_5[63]));
  DFQM2RA \alu_result_in_stage_5_reg[62] (.CK (clk), .D
       (alu_result_out_stage_4[62]), .Q (alu_result_in_stage_5[62]));
  DFQM2RA \alu_result_in_stage_5_reg[5] (.CK (clk), .D
       (alu_result_out_stage_4[5]), .Q (alu_result_in_stage_5[5]));
  DFQM2RA \read_data1_stage_3_reg[63] (.CK (clk), .D
       (read_data1_stage_2[63]), .Q (read_data1_stage_3[63]));
  DFQM2RA \immediate_stage_3_reg[43] (.CK (clk), .D
       (immediate_stage_2[43]), .Q (immediate_stage_3[43]));
  DFQM2RA \alu_result_in_stage_5_reg[61] (.CK (clk), .D
       (alu_result_out_stage_4[61]), .Q (alu_result_in_stage_5[61]));
  DFQM2RA \alu_result_in_stage_5_reg[60] (.CK (clk), .D
       (alu_result_out_stage_4[60]), .Q (alu_result_in_stage_5[60]));
  DFQM2RA \immediate_stage_3_reg[42] (.CK (clk), .D
       (immediate_stage_2[42]), .Q (immediate_stage_3[42]));
  DFQM2RA \alu_result_in_stage_5_reg[59] (.CK (clk), .D
       (alu_result_out_stage_4[59]), .Q (alu_result_in_stage_5[59]));
  DFQM2RA \alu_result_in_stage_5_reg[58] (.CK (clk), .D
       (alu_result_out_stage_4[58]), .Q (alu_result_in_stage_5[58]));
  DFQM2RA \immediate_stage_3_reg[17] (.CK (clk), .D
       (immediate_stage_2[17]), .Q (immediate_stage_3[17]));
  DFQM2RA \instruction_stage_2_reg[15] (.CK (clk), .D
       (instruction_stage_1[15]), .Q (instruction_stage_2[15]));
  DFQM2RA \read_data1_stage_3_reg[62] (.CK (clk), .D
       (read_data1_stage_2[62]), .Q (read_data1_stage_3[62]));
  DFQM2RA \immediate_stage_3_reg[41] (.CK (clk), .D
       (immediate_stage_2[41]), .Q (immediate_stage_3[41]));
  DFQM2RA \alu_result_in_stage_5_reg[11] (.CK (clk), .D
       (alu_result_out_stage_4[11]), .Q (alu_result_in_stage_5[11]));
  DFQM2RA \alu_result_in_stage_5_reg[57] (.CK (clk), .D
       (alu_result_out_stage_4[57]), .Q (alu_result_in_stage_5[57]));
  DFQM2RA \alu_result_in_stage_5_reg[56] (.CK (clk), .D
       (alu_result_out_stage_4[56]), .Q (alu_result_in_stage_5[56]));
  DFQM2RA \immediate_stage_3_reg[40] (.CK (clk), .D
       (immediate_stage_2[40]), .Q (immediate_stage_3[40]));
  DFQM2RA \immediate_stage_3_reg[19] (.CK (clk), .D
       (immediate_stage_2[19]), .Q (immediate_stage_3[19]));
  DFQM2RA \alu_result_in_stage_5_reg[55] (.CK (clk), .D
       (alu_result_out_stage_4[55]), .Q (alu_result_in_stage_5[55]));
  DFQM2RA \alu_result_in_stage_5_reg[54] (.CK (clk), .D
       (alu_result_out_stage_4[54]), .Q (alu_result_in_stage_5[54]));
  DFQM2RA \read_data1_stage_3_reg[61] (.CK (clk), .D
       (read_data1_stage_2[61]), .Q (read_data1_stage_3[61]));
  DFQM2RA \immediate_stage_3_reg[39] (.CK (clk), .D
       (immediate_stage_2[39]), .Q (immediate_stage_3[39]));
  DFQM2RA \alu_result_in_stage_5_reg[53] (.CK (clk), .D
       (alu_result_out_stage_4[53]), .Q (alu_result_in_stage_5[53]));
  DFQM2RA \alu_result_in_stage_5_reg[52] (.CK (clk), .D
       (alu_result_out_stage_4[52]), .Q (alu_result_in_stage_5[52]));
  DFQM2RA \immediate_stage_3_reg[38] (.CK (clk), .D
       (immediate_stage_2[38]), .Q (immediate_stage_3[38]));
  DFQM2RA \read_data1_stage_3_reg[52] (.CK (clk), .D
       (read_data1_stage_2[52]), .Q (read_data1_stage_3[52]));
  DFQM2RA \sum_in_stage_4_reg[33] (.CK (clk), .D (sum_stage_3[33]), .Q
       (sum_in_stage_4[33]));
  DFQM2RA \alu_result_in_stage_5_reg[50] (.CK (clk), .D
       (alu_result_out_stage_4[50]), .Q (alu_result_in_stage_5[50]));
  DFQM2RA \pc_in_stage_2_reg[23] (.CK (clk), .D (pc_out_stage_1[23]),
       .Q (pc_in_stage_2[23]));
  DFQM2RA \alu_result_in_stage_5_reg[19] (.CK (clk), .D
       (alu_result_out_stage_4[19]), .Q (alu_result_in_stage_5[19]));
  DFQM2RA \instruction_stage_2_reg[14] (.CK (clk), .D
       (instruction_stage_1[14]), .Q (instruction_stage_2[14]));
  DFQM2RA \read_data1_stage_3_reg[60] (.CK (clk), .D
       (read_data1_stage_2[60]), .Q (read_data1_stage_3[60]));
  DFQM2RA \immediate_stage_3_reg[37] (.CK (clk), .D
       (immediate_stage_2[37]), .Q (immediate_stage_3[37]));
  DFQM2RA \immediate_stage_3_reg[23] (.CK (clk), .D
       (immediate_stage_2[23]), .Q (immediate_stage_3[23]));
  DFQM2RA \alu_result_in_stage_5_reg[49] (.CK (clk), .D
       (alu_result_out_stage_4[49]), .Q (alu_result_in_stage_5[49]));
  DFQM2RA \alu_result_in_stage_5_reg[48] (.CK (clk), .D
       (alu_result_out_stage_4[48]), .Q (alu_result_in_stage_5[48]));
  DFQM2RA \immediate_stage_3_reg[36] (.CK (clk), .D
       (immediate_stage_2[36]), .Q (immediate_stage_3[36]));
  DFQM2RA \alu_result_in_stage_5_reg[47] (.CK (clk), .D
       (alu_result_out_stage_4[47]), .Q (alu_result_in_stage_5[47]));
  DFQM2RA \alu_result_in_stage_5_reg[46] (.CK (clk), .D
       (alu_result_out_stage_4[46]), .Q (alu_result_in_stage_5[46]));
  DFQM2RA \read_data1_stage_3_reg[59] (.CK (clk), .D
       (read_data1_stage_2[59]), .Q (read_data1_stage_3[59]));
  DFQM2RA \immediate_stage_3_reg[35] (.CK (clk), .D
       (immediate_stage_2[35]), .Q (immediate_stage_3[35]));
  DFQM2RA \read_data1_stage_3_reg[54] (.CK (clk), .D
       (read_data1_stage_2[54]), .Q (read_data1_stage_3[54]));
  DFQM2RA \alu_result_in_stage_5_reg[45] (.CK (clk), .D
       (alu_result_out_stage_4[45]), .Q (alu_result_in_stage_5[45]));
  DFQM2RA \alu_result_in_stage_5_reg[44] (.CK (clk), .D
       (alu_result_out_stage_4[44]), .Q (alu_result_in_stage_5[44]));
  DFQM2RA \immediate_stage_3_reg[34] (.CK (clk), .D
       (immediate_stage_2[34]), .Q (immediate_stage_3[34]));
  DFQM2RA \immediate_stage_3_reg[26] (.CK (clk), .D
       (immediate_stage_2[26]), .Q (immediate_stage_3[26]));
  DFQM2RA \alu_result_in_stage_5_reg[43] (.CK (clk), .D
       (alu_result_out_stage_4[43]), .Q (alu_result_in_stage_5[43]));
  DFQM2RA \alu_result_in_stage_5_reg[42] (.CK (clk), .D
       (alu_result_out_stage_4[42]), .Q (alu_result_in_stage_5[42]));
  DFQM2RA \instruction_stage_2_reg[13] (.CK (clk), .D
       (instruction_stage_1[13]), .Q (instruction_stage_2[13]));
  DFQM2RA \read_data1_stage_3_reg[55] (.CK (clk), .D
       (read_data1_stage_2[55]), .Q (read_data1_stage_3[55]));
  DFQM2RA \read_data1_stage_3_reg[58] (.CK (clk), .D
       (read_data1_stage_2[58]), .Q (read_data1_stage_3[58]));
  DFQM2RA \immediate_stage_3_reg[33] (.CK (clk), .D
       (immediate_stage_2[33]), .Q (immediate_stage_3[33]));
  DFQM2RA \alu_result_in_stage_5_reg[41] (.CK (clk), .D
       (alu_result_out_stage_4[41]), .Q (alu_result_in_stage_5[41]));
  DFQM2RA \alu_result_in_stage_5_reg[40] (.CK (clk), .D
       (alu_result_out_stage_4[40]), .Q (alu_result_in_stage_5[40]));
  DFQM2RA \immediate_stage_3_reg[32] (.CK (clk), .D
       (immediate_stage_2[32]), .Q (immediate_stage_3[32]));
  DFQM2RA \alu_result_in_stage_5_reg[39] (.CK (clk), .D
       (alu_result_out_stage_4[39]), .Q (alu_result_in_stage_5[39]));
  DFQM2RA \alu_result_in_stage_5_reg[38] (.CK (clk), .D
       (alu_result_out_stage_4[38]), .Q (alu_result_in_stage_5[38]));
  DFQM2RA \read_data1_stage_3_reg[57] (.CK (clk), .D
       (read_data1_stage_2[57]), .Q (read_data1_stage_3[57]));
  DFQM2RA \immediate_stage_3_reg[31] (.CK (clk), .D
       (immediate_stage_2[31]), .Q (immediate_stage_3[31]));
  DFQM2RA \alu_result_in_stage_5_reg[37] (.CK (clk), .D
       (alu_result_out_stage_4[37]), .Q (alu_result_in_stage_5[37]));
  DFQM2RA \alu_result_in_stage_5_reg[36] (.CK (clk), .D
       (alu_result_out_stage_4[36]), .Q (alu_result_in_stage_5[36]));
  DFQM2RA \immediate_stage_3_reg[30] (.CK (clk), .D
       (immediate_stage_2[30]), .Q (immediate_stage_3[30]));
  DFQM2RA \alu_result_in_stage_5_reg[35] (.CK (clk), .D
       (alu_result_out_stage_4[35]), .Q (alu_result_in_stage_5[35]));
  DFQM2RA \alu_result_in_stage_5_reg[34] (.CK (clk), .D
       (alu_result_out_stage_4[34]), .Q (alu_result_in_stage_5[34]));
  DFQM2RA \pc_in_stage_2_reg[43] (.CK (clk), .D (pc_out_stage_1[43]),
       .Q (pc_in_stage_2[43]));
  DFQM2RA \pc_in_stage_2_reg[22] (.CK (clk), .D (pc_out_stage_1[22]),
       .Q (pc_in_stage_2[22]));
  DFQM2RA \instruction_stage_2_reg[12] (.CK (clk), .D
       (instruction_stage_1[12]), .Q (instruction_stage_2[12]));
  DFQM2RA \read_data1_stage_3_reg[56] (.CK (clk), .D
       (read_data1_stage_2[56]), .Q (read_data1_stage_3[56]));
  DFQM2RA \immediate_stage_3_reg[29] (.CK (clk), .D
       (immediate_stage_2[29]), .Q (immediate_stage_3[29]));
  DFQM2RA \alu_result_in_stage_5_reg[33] (.CK (clk), .D
       (alu_result_out_stage_4[33]), .Q (alu_result_in_stage_5[33]));
  DFQM2RA \alu_result_in_stage_5_reg[32] (.CK (clk), .D
       (alu_result_out_stage_4[32]), .Q (alu_result_in_stage_5[32]));
  DFQM2RA \immediate_stage_3_reg[28] (.CK (clk), .D
       (immediate_stage_2[28]), .Q (immediate_stage_3[28]));
  DFQM2RA \alu_result_in_stage_5_reg[31] (.CK (clk), .D
       (alu_result_out_stage_4[31]), .Q (alu_result_in_stage_5[31]));
  DFQM2RA \alu_result_in_stage_5_reg[30] (.CK (clk), .D
       (alu_result_out_stage_4[30]), .Q (alu_result_in_stage_5[30]));
  DFQM2RA \immediate_stage_3_reg[27] (.CK (clk), .D
       (immediate_stage_2[27]), .Q (immediate_stage_3[27]));
  DFQM2RA \alu_result_in_stage_5_reg[29] (.CK (clk), .D
       (alu_result_out_stage_4[29]), .Q (alu_result_in_stage_5[29]));
  DFQM2RA \alu_result_in_stage_5_reg[28] (.CK (clk), .D
       (alu_result_out_stage_4[28]), .Q (alu_result_in_stage_5[28]));
  DFQM2RA \alu_result_in_stage_5_reg[27] (.CK (clk), .D
       (alu_result_out_stage_4[27]), .Q (alu_result_in_stage_5[27]));
  DFQM2RA \alu_result_in_stage_5_reg[26] (.CK (clk), .D
       (alu_result_out_stage_4[26]), .Q (alu_result_in_stage_5[26]));
  DFQM2RA \instruction_stage_2_reg[11] (.CK (clk), .D
       (instruction_stage_1[11]), .Q (instruction_stage_2[11]));
  DFQM2RA \immediate_stage_3_reg[25] (.CK (clk), .D
       (immediate_stage_2[25]), .Q (immediate_stage_3[25]));
  DFQM2RA \alu_result_in_stage_5_reg[25] (.CK (clk), .D
       (alu_result_out_stage_4[25]), .Q (alu_result_in_stage_5[25]));
  DFQM2RA \alu_result_in_stage_5_reg[24] (.CK (clk), .D
       (alu_result_out_stage_4[24]), .Q (alu_result_in_stage_5[24]));
  DFQM2RA \immediate_stage_3_reg[24] (.CK (clk), .D
       (immediate_stage_2[24]), .Q (immediate_stage_3[24]));
  DFQM2RA \alu_result_in_stage_5_reg[23] (.CK (clk), .D
       (alu_result_out_stage_4[23]), .Q (alu_result_in_stage_5[23]));
  DFQM2RA \alu_result_in_stage_5_reg[22] (.CK (clk), .D
       (alu_result_out_stage_4[22]), .Q (alu_result_in_stage_5[22]));
  DFQM2RA \read_data1_stage_3_reg[53] (.CK (clk), .D
       (read_data1_stage_2[53]), .Q (read_data1_stage_3[53]));
  DFQM2RA \alu_result_in_stage_5_reg[21] (.CK (clk), .D
       (alu_result_out_stage_4[21]), .Q (alu_result_in_stage_5[21]));
  DFQM2RA \alu_result_in_stage_5_reg[20] (.CK (clk), .D
       (alu_result_out_stage_4[20]), .Q (alu_result_in_stage_5[20]));
  DFQM2RA \immediate_stage_3_reg[22] (.CK (clk), .D
       (immediate_stage_2[22]), .Q (immediate_stage_3[22]));
  DFQM2RA \sum_in_stage_4_reg[12] (.CK (clk), .D (sum_stage_3[12]), .Q
       (sum_in_stage_4[12]));
  DFQM2RA \pc_in_stage_2_reg[21] (.CK (clk), .D (pc_out_stage_1[21]),
       .Q (pc_in_stage_2[21]));
  DFQM2RA \instruction_stage_2_reg[10] (.CK (clk), .D
       (instruction_stage_1[10]), .Q (instruction_stage_2[10]));
  DFQM2RA \immediate_stage_3_reg[21] (.CK (clk), .D
       (immediate_stage_2[21]), .Q (immediate_stage_3[21]));
  DFQM2RA \alu_result_in_stage_5_reg[17] (.CK (clk), .D
       (alu_result_out_stage_4[17]), .Q (alu_result_in_stage_5[17]));
  DFQM2RA \alu_result_in_stage_5_reg[16] (.CK (clk), .D
       (alu_result_out_stage_4[16]), .Q (alu_result_in_stage_5[16]));
  DFQM2RA \immediate_stage_3_reg[20] (.CK (clk), .D
       (immediate_stage_2[20]), .Q (immediate_stage_3[20]));
  DFQM2RA \alu_result_in_stage_5_reg[15] (.CK (clk), .D
       (alu_result_out_stage_4[15]), .Q (alu_result_in_stage_5[15]));
  DFQM2RA \alu_result_in_stage_5_reg[14] (.CK (clk), .D
       (alu_result_out_stage_4[14]), .Q (alu_result_in_stage_5[14]));
  DFQM2RA \read_data1_stage_3_reg[51] (.CK (clk), .D
       (read_data1_stage_2[51]), .Q (read_data1_stage_3[51]));
  DFQM2RA \alu_result_in_stage_5_reg[13] (.CK (clk), .D
       (alu_result_out_stage_4[13]), .Q (alu_result_in_stage_5[13]));
  DFQM2RA \alu_result_in_stage_5_reg[12] (.CK (clk), .D
       (alu_result_out_stage_4[12]), .Q (alu_result_in_stage_5[12]));
  DFQM2RA \immediate_stage_3_reg[18] (.CK (clk), .D
       (immediate_stage_2[18]), .Q (immediate_stage_3[18]));
  DFQM2RA \alu_result_in_stage_5_reg[10] (.CK (clk), .D
       (alu_result_out_stage_4[10]), .Q (alu_result_in_stage_5[10]));
  DFQM2RA \instruction_stage_2_reg[9] (.CK (clk), .D
       (instruction_stage_1[9]), .Q (instruction_stage_2[9]));
  DFQM2RA \read_data1_stage_3_reg[50] (.CK (clk), .D
       (read_data1_stage_2[50]), .Q (read_data1_stage_3[50]));
  DFQM2RA \alu_result_in_stage_5_reg[9] (.CK (clk), .D
       (alu_result_out_stage_4[9]), .Q (alu_result_in_stage_5[9]));
  DFQM2RA \alu_result_in_stage_5_reg[8] (.CK (clk), .D
       (alu_result_out_stage_4[8]), .Q (alu_result_in_stage_5[8]));
  DFQM2RA \immediate_stage_3_reg[16] (.CK (clk), .D
       (immediate_stage_2[16]), .Q (immediate_stage_3[16]));
  DFQM2RA \alu_result_in_stage_5_reg[7] (.CK (clk), .D
       (alu_result_out_stage_4[7]), .Q (alu_result_in_stage_5[7]));
  DFQM2RA \alu_result_in_stage_5_reg[6] (.CK (clk), .D
       (alu_result_out_stage_4[6]), .Q (alu_result_in_stage_5[6]));
  DFQM2RA \read_data1_stage_3_reg[49] (.CK (clk), .D
       (read_data1_stage_2[49]), .Q (read_data1_stage_3[49]));
  DFQM2RA \immediate_stage_3_reg[15] (.CK (clk), .D
       (immediate_stage_2[15]), .Q (immediate_stage_3[15]));
  DFQM2RA \alu_result_in_stage_5_reg[4] (.CK (clk), .D
       (alu_result_out_stage_4[4]), .Q (alu_result_in_stage_5[4]));
  DFQM2RA \immediate_stage_3_reg[14] (.CK (clk), .D
       (immediate_stage_2[14]), .Q (immediate_stage_3[14]));
  DFQM2RA \alu_result_in_stage_5_reg[3] (.CK (clk), .D
       (alu_result_out_stage_4[3]), .Q (alu_result_in_stage_5[3]));
  DFQM2RA \pc_in_stage_2_reg[53] (.CK (clk), .D (pc_out_stage_1[53]),
       .Q (pc_in_stage_2[53]));
  DFQM2RA \pc_in_stage_2_reg[42] (.CK (clk), .D (pc_out_stage_1[42]),
       .Q (pc_in_stage_2[42]));
  DFQM2RA \pc_in_stage_2_reg[20] (.CK (clk), .D (pc_out_stage_1[20]),
       .Q (pc_in_stage_2[20]));
  DFQM2RA \read_data1_stage_3_reg[48] (.CK (clk), .D
       (read_data1_stage_2[48]), .Q (read_data1_stage_3[48]));
  DFQM2RA \immediate_stage_3_reg[13] (.CK (clk), .D
       (immediate_stage_2[13]), .Q (immediate_stage_3[13]));
  DFQM2RA \alu_result_in_stage_5_reg[1] (.CK (clk), .D
       (alu_result_out_stage_4[1]), .Q (alu_result_in_stage_5[1]));
  DFQM2RA \alu_result_in_stage_5_reg[0] (.CK (clk), .D
       (alu_result_out_stage_4[0]), .Q (alu_result_in_stage_5[0]));
  DFQM2RA \immediate_stage_3_reg[12] (.CK (clk), .D
       (immediate_stage_2[12]), .Q (immediate_stage_3[12]));
  DFQM2RA MemToReg_in_stage_5_reg(.CK (clk), .D (MemToReg_out_stage_4),
       .Q (MemToReg_in_stage_5));
  DFQM2RA RegWrite_in_stage_5_reg(.CK (clk), .D (RegWrite_out_stage_4),
       .Q (RegWrite_in_stage_5));
  DFQM2RA \immediate_stage_3_reg[11] (.CK (clk), .D
       (immediate_stage_2[11]), .Q (immediate_stage_3[11]));
  DFQM2RA \immediate_stage_3_reg[10] (.CK (clk), .D
       (immediate_stage_2[10]), .Q (immediate_stage_3[10]));
  DFQM2RA \instruction_stage_2_reg[7] (.CK (clk), .D
       (instruction_stage_1[7]), .Q (instruction_stage_2[7]));
  DFQM2RA \immediate_stage_3_reg[9] (.CK (clk), .D
       (immediate_stage_2[9]), .Q (immediate_stage_3[9]));
  DFQM2RA \immediate_stage_3_reg[8] (.CK (clk), .D
       (immediate_stage_2[8]), .Q (immediate_stage_3[8]));
  DFQM2RA \read_data1_stage_3_reg[45] (.CK (clk), .D
       (read_data1_stage_2[45]), .Q (read_data1_stage_3[45]));
  DFQM2RA \immediate_stage_3_reg[6] (.CK (clk), .D
       (immediate_stage_2[6]), .Q (immediate_stage_3[6]));
  DFQM2RA \pc_in_stage_2_reg[19] (.CK (clk), .D (pc_out_stage_1[19]),
       .Q (pc_in_stage_2[19]));
  DFQM2RA \instruction_stage_2_reg[6] (.CK (clk), .D
       (instruction_stage_1[6]), .Q (instruction_stage_2[6]));
  DFQM2RA \read_data1_stage_3_reg[44] (.CK (clk), .D
       (read_data1_stage_2[44]), .Q (read_data1_stage_3[44]));
  DFQM2RA \immediate_stage_3_reg[5] (.CK (clk), .D
       (immediate_stage_2[5]), .Q (immediate_stage_3[5]));
  DFQM2RA \immediate_stage_3_reg[4] (.CK (clk), .D
       (immediate_stage_2[4]), .Q (immediate_stage_3[4]));
  DFQM2RA \read_data1_stage_3_reg[43] (.CK (clk), .D
       (read_data1_stage_2[43]), .Q (read_data1_stage_3[43]));
  DFQM2RA \immediate_stage_3_reg[2] (.CK (clk), .D
       (immediate_stage_2[2]), .Q (immediate_stage_3[2]));
  DFQM2RA \instruction_stage_2_reg[5] (.CK (clk), .D
       (instruction_stage_1[5]), .Q (instruction_stage_2[5]));
  DFQM2RA \read_data1_stage_3_reg[42] (.CK (clk), .D
       (read_data1_stage_2[42]), .Q (read_data1_stage_3[42]));
  DFQM2RA \immediate_stage_3_reg[0] (.CK (clk), .D
       (immediate_stage_2[0]), .Q (immediate_stage_3[0]));
  DFQM2RA \read_data1_stage_3_reg[41] (.CK (clk), .D
       (read_data1_stage_2[41]), .Q (read_data1_stage_3[41]));
  DFQM2RA \ALU_control_input_stage_3_reg[3] (.CK (clk), .D
       (ALU_control_input_stage_2[3]), .Q
       (ALU_control_input_stage_3[3]));
  DFQM2RA \pc_in_stage_2_reg[41] (.CK (clk), .D (pc_out_stage_1[41]),
       .Q (pc_in_stage_2[41]));
  DFQM2RA \pc_in_stage_2_reg[18] (.CK (clk), .D (pc_out_stage_1[18]),
       .Q (pc_in_stage_2[18]));
  DFQM2RA \instruction_stage_2_reg[4] (.CK (clk), .D
       (instruction_stage_1[4]), .Q (instruction_stage_2[4]));
  DFQM2RA \read_data1_stage_3_reg[40] (.CK (clk), .D
       (read_data1_stage_2[40]), .Q (read_data1_stage_3[40]));
  DFQM2RA \ALU_control_input_stage_3_reg[1] (.CK (clk), .D
       (ALU_control_input_stage_2[1]), .Q
       (ALU_control_input_stage_3[1]));
  DFQM2RA \ALU_control_input_stage_3_reg[0] (.CK (clk), .D
       (ALU_control_input_stage_2[0]), .Q
       (ALU_control_input_stage_3[0]));
  DFQM2RA \read_data1_stage_3_reg[39] (.CK (clk), .D
       (read_data1_stage_2[39]), .Q (read_data1_stage_3[39]));
  DFQM2RA \sum_in_stage_4_reg[62] (.CK (clk), .D (sum_stage_3[62]), .Q
       (sum_in_stage_4[62]));
  DFQM2RA \instruction_stage_2_reg[3] (.CK (clk), .D
       (instruction_stage_1[3]), .Q (instruction_stage_2[3]));
  DFQM2RA \read_data1_stage_3_reg[38] (.CK (clk), .D
       (read_data1_stage_2[38]), .Q (read_data1_stage_3[38]));
  DFQM2RA \sum_in_stage_4_reg[60] (.CK (clk), .D (sum_stage_3[60]), .Q
       (sum_in_stage_4[60]));
  DFQM2RA \read_data1_stage_3_reg[37] (.CK (clk), .D
       (read_data1_stage_2[37]), .Q (read_data1_stage_3[37]));
  DFQM2RA \sum_in_stage_4_reg[59] (.CK (clk), .D (sum_stage_3[59]), .Q
       (sum_in_stage_4[59]));
  DFQM2RA \pc_in_stage_2_reg[17] (.CK (clk), .D (pc_out_stage_1[17]),
       .Q (pc_in_stage_2[17]));
  DFQM2RA \instruction_stage_2_reg[2] (.CK (clk), .D
       (instruction_stage_1[2]), .Q (instruction_stage_2[2]));
  DFQM2RA \read_data1_stage_3_reg[36] (.CK (clk), .D
       (read_data1_stage_2[36]), .Q (read_data1_stage_3[36]));
  DFQM2RA \sum_in_stage_4_reg[57] (.CK (clk), .D (sum_stage_3[57]), .Q
       (sum_in_stage_4[57]));
  DFQM2RA \sum_in_stage_4_reg[56] (.CK (clk), .D (sum_stage_3[56]), .Q
       (sum_in_stage_4[56]));
  DFQM2RA \read_data1_stage_3_reg[35] (.CK (clk), .D
       (read_data1_stage_2[35]), .Q (read_data1_stage_3[35]));
  DFQM2RA \sum_in_stage_4_reg[55] (.CK (clk), .D (sum_stage_3[55]), .Q
       (sum_in_stage_4[55]));
  DFQM2RA \sum_in_stage_4_reg[54] (.CK (clk), .D (sum_stage_3[54]), .Q
       (sum_in_stage_4[54]));
  DFQM2RA \instruction_stage_2_reg[1] (.CK (clk), .D
       (instruction_stage_1[1]), .Q (instruction_stage_2[1]));
  DFQM2RA \read_data1_stage_3_reg[34] (.CK (clk), .D
       (read_data1_stage_2[34]), .Q (read_data1_stage_3[34]));
  DFQM2RA \sum_in_stage_4_reg[53] (.CK (clk), .D (sum_stage_3[53]), .Q
       (sum_in_stage_4[53]));
  DFQM2RA \read_data1_stage_3_reg[33] (.CK (clk), .D
       (read_data1_stage_2[33]), .Q (read_data1_stage_3[33]));
  DFQM2RA \sum_in_stage_4_reg[51] (.CK (clk), .D (sum_stage_3[51]), .Q
       (sum_in_stage_4[51]));
  DFQM2RA \sum_in_stage_4_reg[50] (.CK (clk), .D (sum_stage_3[50]), .Q
       (sum_in_stage_4[50]));
  DFQM2RA \pc_in_stage_2_reg[58] (.CK (clk), .D (pc_out_stage_1[58]),
       .Q (pc_in_stage_2[58]));
  DFQM2RA \pc_in_stage_2_reg[52] (.CK (clk), .D (pc_out_stage_1[52]),
       .Q (pc_in_stage_2[52]));
  DFQM2RA \pc_in_stage_2_reg[40] (.CK (clk), .D (pc_out_stage_1[40]),
       .Q (pc_in_stage_2[40]));
  DFQM2RA \pc_in_stage_2_reg[16] (.CK (clk), .D (pc_out_stage_1[16]),
       .Q (pc_in_stage_2[16]));
  DFQM2RA \instruction_stage_2_reg[0] (.CK (clk), .D
       (instruction_stage_1[0]), .Q (instruction_stage_2[0]));
  DFQM2RA \read_data1_stage_3_reg[32] (.CK (clk), .D
       (read_data1_stage_2[32]), .Q (read_data1_stage_3[32]));
  DFQM2RA \sum_in_stage_4_reg[49] (.CK (clk), .D (sum_stage_3[49]), .Q
       (sum_in_stage_4[49]));
  DFQM2RA \read_data1_stage_3_reg[31] (.CK (clk), .D
       (read_data1_stage_2[31]), .Q (read_data1_stage_3[31]));
  DFQM2RA \sum_in_stage_4_reg[47] (.CK (clk), .D (sum_stage_3[47]), .Q
       (sum_in_stage_4[47]));
  DFQM2RA \sum_in_stage_4_reg[46] (.CK (clk), .D (sum_stage_3[46]), .Q
       (sum_in_stage_4[46]));
  DFQM2RA \read_data1_stage_3_reg[30] (.CK (clk), .D
       (read_data1_stage_2[30]), .Q (read_data1_stage_3[30]));
  DFQM2RA \sum_in_stage_4_reg[45] (.CK (clk), .D (sum_stage_3[45]), .Q
       (sum_in_stage_4[45]));
  DFQM2RA \sum_in_stage_4_reg[44] (.CK (clk), .D (sum_stage_3[44]), .Q
       (sum_in_stage_4[44]));
  DFQM2RA \sum_in_stage_4_reg[43] (.CK (clk), .D (sum_stage_3[43]), .Q
       (sum_in_stage_4[43]));
  DFQM2RA \sum_in_stage_4_reg[42] (.CK (clk), .D (sum_stage_3[42]), .Q
       (sum_in_stage_4[42]));
  DFQM2RA \pc_in_stage_2_reg[15] (.CK (clk), .D (pc_out_stage_1[15]),
       .Q (pc_in_stage_2[15]));
  DFQM2RA \pc_in_stage_3_reg[62] (.CK (clk), .D (pc_out_stage_2[62]),
       .Q (pc_in_stage_3[62]));
  DFQM2RA \read_data1_stage_3_reg[28] (.CK (clk), .D
       (read_data1_stage_2[28]), .Q (read_data1_stage_3[28]));
  DFQM2RA \sum_in_stage_4_reg[41] (.CK (clk), .D (sum_stage_3[41]), .Q
       (sum_in_stage_4[41]));
  DFQM2RA \sum_in_stage_4_reg[40] (.CK (clk), .D (sum_stage_3[40]), .Q
       (sum_in_stage_4[40]));
  DFQM2RA \sum_in_stage_4_reg[39] (.CK (clk), .D (sum_stage_3[39]), .Q
       (sum_in_stage_4[39]));
  DFQM2RA \sum_in_stage_4_reg[38] (.CK (clk), .D (sum_stage_3[38]), .Q
       (sum_in_stage_4[38]));
  DFQM2RA \pc_in_stage_3_reg[61] (.CK (clk), .D (pc_out_stage_2[61]),
       .Q (pc_in_stage_3[61]));
  DFQM2RA \sum_in_stage_4_reg[37] (.CK (clk), .D (sum_stage_3[37]), .Q
       (sum_in_stage_4[37]));
  DFQM2RA \sum_in_stage_4_reg[36] (.CK (clk), .D (sum_stage_3[36]), .Q
       (sum_in_stage_4[36]));
  DFQM2RA \read_data1_stage_3_reg[25] (.CK (clk), .D
       (read_data1_stage_2[25]), .Q (read_data1_stage_3[25]));
  DFQM2RA \sum_in_stage_4_reg[34] (.CK (clk), .D (sum_stage_3[34]), .Q
       (sum_in_stage_4[34]));
  DFQM2RA \pc_in_stage_2_reg[39] (.CK (clk), .D (pc_out_stage_1[39]),
       .Q (pc_in_stage_2[39]));
  DFQM2RA \pc_in_stage_2_reg[14] (.CK (clk), .D (pc_out_stage_1[14]),
       .Q (pc_in_stage_2[14]));
  DFQM2RA \pc_in_stage_3_reg[60] (.CK (clk), .D (pc_out_stage_2[60]),
       .Q (pc_in_stage_3[60]));
  DFQM2RA \read_data1_stage_3_reg[24] (.CK (clk), .D
       (read_data1_stage_2[24]), .Q (read_data1_stage_3[24]));
  DFQM2RA \alu_result_in_stage_5_reg[51] (.CK (clk), .D
       (alu_result_out_stage_4[51]), .Q (alu_result_in_stage_5[51]));
  DFQM2RA \sum_in_stage_4_reg[32] (.CK (clk), .D (sum_stage_3[32]), .Q
       (sum_in_stage_4[32]));
  DFQM2RA \sum_in_stage_4_reg[31] (.CK (clk), .D (sum_stage_3[31]), .Q
       (sum_in_stage_4[31]));
  DFQM2RA \sum_in_stage_4_reg[30] (.CK (clk), .D (sum_stage_3[30]), .Q
       (sum_in_stage_4[30]));
  DFQM2RA \pc_in_stage_3_reg[59] (.CK (clk), .D (pc_out_stage_2[59]),
       .Q (pc_in_stage_3[59]));
  DFQM2RA \sum_in_stage_4_reg[29] (.CK (clk), .D (sum_stage_3[29]), .Q
       (sum_in_stage_4[29]));
  DFQM2RA \sum_in_stage_4_reg[28] (.CK (clk), .D (sum_stage_3[28]), .Q
       (sum_in_stage_4[28]));
  DFQM2RA \read_data1_stage_3_reg[21] (.CK (clk), .D
       (read_data1_stage_2[21]), .Q (read_data1_stage_3[21]));
  DFQM2RA \sum_in_stage_4_reg[26] (.CK (clk), .D (sum_stage_3[26]), .Q
       (sum_in_stage_4[26]));
  DFQM2RA \pc_in_stage_2_reg[13] (.CK (clk), .D (pc_out_stage_1[13]),
       .Q (pc_in_stage_2[13]));
  DFQM2RA \pc_in_stage_3_reg[58] (.CK (clk), .D (pc_out_stage_2[58]),
       .Q (pc_in_stage_3[58]));
  DFQM2RA \read_data1_stage_3_reg[20] (.CK (clk), .D
       (read_data1_stage_2[20]), .Q (read_data1_stage_3[20]));
  DFQM2RA \sum_in_stage_4_reg[25] (.CK (clk), .D (sum_stage_3[25]), .Q
       (sum_in_stage_4[25]));
  DFQM2RA \sum_in_stage_4_reg[24] (.CK (clk), .D (sum_stage_3[24]), .Q
       (sum_in_stage_4[24]));
  DFQM2RA \read_data1_stage_3_reg[19] (.CK (clk), .D
       (read_data1_stage_2[19]), .Q (read_data1_stage_3[19]));
  DFQM2RA \sum_in_stage_4_reg[22] (.CK (clk), .D (sum_stage_3[22]), .Q
       (sum_in_stage_4[22]));
  DFQM2RA \pc_in_stage_3_reg[57] (.CK (clk), .D (pc_out_stage_2[57]),
       .Q (pc_in_stage_3[57]));
  DFQM2RA \read_data1_stage_3_reg[18] (.CK (clk), .D
       (read_data1_stage_2[18]), .Q (read_data1_stage_3[18]));
  DFQM2RA \sum_in_stage_4_reg[20] (.CK (clk), .D (sum_stage_3[20]), .Q
       (sum_in_stage_4[20]));
  DFQM2RA \read_data1_stage_3_reg[17] (.CK (clk), .D
       (read_data1_stage_2[17]), .Q (read_data1_stage_3[17]));
  DFQM2RA \sum_in_stage_4_reg[19] (.CK (clk), .D (sum_stage_3[19]), .Q
       (sum_in_stage_4[19]));
  DFQM2RA \pc_in_stage_2_reg[51] (.CK (clk), .D (pc_out_stage_1[51]),
       .Q (pc_in_stage_2[51]));
  DFQM2RA \pc_in_stage_2_reg[38] (.CK (clk), .D (pc_out_stage_1[38]),
       .Q (pc_in_stage_2[38]));
  DFQM2RA \pc_in_stage_2_reg[12] (.CK (clk), .D (pc_out_stage_1[12]),
       .Q (pc_in_stage_2[12]));
  DFQM2RA \pc_in_stage_3_reg[56] (.CK (clk), .D (pc_out_stage_2[56]),
       .Q (pc_in_stage_3[56]));
  DFQM2RA \read_data1_stage_3_reg[16] (.CK (clk), .D
       (read_data1_stage_2[16]), .Q (read_data1_stage_3[16]));
  DFQM2RA \sum_in_stage_4_reg[17] (.CK (clk), .D (sum_stage_3[17]), .Q
       (sum_in_stage_4[17]));
  DFQM2RA \sum_in_stage_4_reg[16] (.CK (clk), .D (sum_stage_3[16]), .Q
       (sum_in_stage_4[16]));
  DFQM2RA \sum_in_stage_4_reg[15] (.CK (clk), .D (sum_stage_3[15]), .Q
       (sum_in_stage_4[15]));
  DFQM2RA \sum_in_stage_4_reg[14] (.CK (clk), .D (sum_stage_3[14]), .Q
       (sum_in_stage_4[14]));
  DFQM2RA \pc_in_stage_3_reg[55] (.CK (clk), .D (pc_out_stage_2[55]),
       .Q (pc_in_stage_3[55]));
  DFQM2RA \sum_in_stage_4_reg[13] (.CK (clk), .D (sum_stage_3[13]), .Q
       (sum_in_stage_4[13]));
  DFQM2RA \alu_result_in_stage_5_reg[18] (.CK (clk), .D
       (alu_result_out_stage_4[18]), .Q (alu_result_in_stage_5[18]));
  DFQM2RA \read_data1_stage_3_reg[13] (.CK (clk), .D
       (read_data1_stage_2[13]), .Q (read_data1_stage_3[13]));
  DFQM2RA \sum_in_stage_4_reg[10] (.CK (clk), .D (sum_stage_3[10]), .Q
       (sum_in_stage_4[10]));
  DFQM2RA \pc_in_stage_2_reg[11] (.CK (clk), .D (pc_out_stage_1[11]),
       .Q (pc_in_stage_2[11]));
  DFQM2RA \pc_in_stage_3_reg[54] (.CK (clk), .D (pc_out_stage_2[54]),
       .Q (pc_in_stage_3[54]));
  DFQM2RA \read_data1_stage_3_reg[12] (.CK (clk), .D
       (read_data1_stage_2[12]), .Q (read_data1_stage_3[12]));
  DFQM2RA \sum_in_stage_4_reg[9] (.CK (clk), .D (sum_stage_3[9]), .Q
       (sum_in_stage_4[9]));
  DFQM2RA \sum_in_stage_4_reg[8] (.CK (clk), .D (sum_stage_3[8]), .Q
       (sum_in_stage_4[8]));
  DFQM2RA \read_data1_stage_3_reg[11] (.CK (clk), .D
       (read_data1_stage_2[11]), .Q (read_data1_stage_3[11]));
  DFQM2RA \sum_in_stage_4_reg[6] (.CK (clk), .D (sum_stage_3[6]), .Q
       (sum_in_stage_4[6]));
  DFQM2RA \pc_in_stage_3_reg[53] (.CK (clk), .D (pc_out_stage_2[53]),
       .Q (pc_in_stage_3[53]));
  DFQM2RA \read_data1_stage_3_reg[10] (.CK (clk), .D
       (read_data1_stage_2[10]), .Q (read_data1_stage_3[10]));
  DFQM2RA \sum_in_stage_4_reg[4] (.CK (clk), .D (sum_stage_3[4]), .Q
       (sum_in_stage_4[4]));
  DFQM2RA \read_data1_stage_3_reg[9] (.CK (clk), .D
       (read_data1_stage_2[9]), .Q (read_data1_stage_3[9]));
  DFQM2RA \sum_in_stage_4_reg[3] (.CK (clk), .D (sum_stage_3[3]), .Q
       (sum_in_stage_4[3]));
  DFQM2RA \pc_in_stage_2_reg[37] (.CK (clk), .D (pc_out_stage_1[37]),
       .Q (pc_in_stage_2[37]));
  DFQM2RA \pc_in_stage_2_reg[10] (.CK (clk), .D (pc_out_stage_1[10]),
       .Q (pc_in_stage_2[10]));
  DFQM2RA \pc_in_stage_3_reg[52] (.CK (clk), .D (pc_out_stage_2[52]),
       .Q (pc_in_stage_3[52]));
  DFQM2RA \read_data1_stage_3_reg[8] (.CK (clk), .D
       (read_data1_stage_2[8]), .Q (read_data1_stage_3[8]));
  DFQM2RA \sum_in_stage_4_reg[1] (.CK (clk), .D (sum_stage_3[1]), .Q
       (sum_in_stage_4[1]));
  DFQM2RA \sum_in_stage_4_reg[0] (.CK (clk), .D (sum_stage_3[0]), .Q
       (sum_in_stage_4[0]));
  DFQM2RA \read_data1_stage_3_reg[7] (.CK (clk), .D
       (read_data1_stage_2[7]), .Q (read_data1_stage_3[7]));
  DFQM2RA \alu_result_in_stage_4_reg[63] (.CK (clk), .D
       (alu_result_stage_3[63]), .Q (alu_result_in_stage_4[63]));
  DFQM2RA \pc_in_stage_3_reg[51] (.CK (clk), .D (pc_out_stage_2[51]),
       .Q (pc_in_stage_3[51]));
  DFQM2RA \read_data1_stage_3_reg[6] (.CK (clk), .D
       (read_data1_stage_2[6]), .Q (read_data1_stage_3[6]));
  DFQM2RA \alu_result_in_stage_4_reg[61] (.CK (clk), .D
       (alu_result_stage_3[61]), .Q (alu_result_in_stage_4[61]));
  DFQM2RA \read_data1_stage_3_reg[5] (.CK (clk), .D
       (read_data1_stage_2[5]), .Q (read_data1_stage_3[5]));
  DFQM2RA \alu_result_in_stage_4_reg[60] (.CK (clk), .D
       (alu_result_stage_3[60]), .Q (alu_result_in_stage_4[60]));
  DFQM2RA \pc_in_stage_2_reg[9] (.CK (clk), .D (pc_out_stage_1[9]), .Q
       (pc_in_stage_2[9]));
  DFQM2RA \pc_in_stage_3_reg[50] (.CK (clk), .D (pc_out_stage_2[50]),
       .Q (pc_in_stage_3[50]));
  DFQM2RA \read_data1_stage_3_reg[4] (.CK (clk), .D
       (read_data1_stage_2[4]), .Q (read_data1_stage_3[4]));
  DFQM2RA \alu_result_in_stage_4_reg[58] (.CK (clk), .D
       (alu_result_stage_3[58]), .Q (alu_result_in_stage_4[58]));
  DFQM2RA \alu_result_in_stage_4_reg[57] (.CK (clk), .D
       (alu_result_stage_3[57]), .Q (alu_result_in_stage_4[57]));
  DFQM2RA \read_data1_stage_3_reg[3] (.CK (clk), .D
       (read_data1_stage_2[3]), .Q (read_data1_stage_3[3]));
  DFQM2RA \alu_result_in_stage_4_reg[56] (.CK (clk), .D
       (alu_result_stage_3[56]), .Q (alu_result_in_stage_4[56]));
  DFQM2RA \pc_in_stage_3_reg[49] (.CK (clk), .D (pc_out_stage_2[49]),
       .Q (pc_in_stage_3[49]));
  DFQM2RA \read_data1_stage_3_reg[2] (.CK (clk), .D
       (read_data1_stage_2[2]), .Q (read_data1_stage_3[2]));
  DFQM2RA \alu_result_in_stage_4_reg[54] (.CK (clk), .D
       (alu_result_stage_3[54]), .Q (alu_result_in_stage_4[54]));
  DFQM2RA \read_data1_stage_3_reg[1] (.CK (clk), .D
       (read_data1_stage_2[1]), .Q (read_data1_stage_3[1]));
  DFQM2RA \alu_result_in_stage_4_reg[52] (.CK (clk), .D
       (alu_result_stage_3[52]), .Q (alu_result_in_stage_4[52]));
  DFQM2RA \alu_result_in_stage_4_reg[51] (.CK (clk), .D
       (alu_result_stage_3[51]), .Q (alu_result_in_stage_4[51]));
  DFQM2RA \pc_in_stage_2_reg[50] (.CK (clk), .D (pc_out_stage_1[50]),
       .Q (pc_in_stage_2[50]));
  DFQM2RA \pc_in_stage_2_reg[36] (.CK (clk), .D (pc_out_stage_1[36]),
       .Q (pc_in_stage_2[36]));
  DFQM2RA \pc_in_stage_2_reg[8] (.CK (clk), .D (pc_out_stage_1[8]), .Q
       (pc_in_stage_2[8]));
  DFQM2RA \pc_in_stage_3_reg[48] (.CK (clk), .D (pc_out_stage_2[48]),
       .Q (pc_in_stage_3[48]));
  DFQM2RA \read_data1_stage_3_reg[0] (.CK (clk), .D
       (read_data1_stage_2[0]), .Q (read_data1_stage_3[0]));
  DFQM2RA \alu_result_in_stage_4_reg[50] (.CK (clk), .D
       (alu_result_stage_3[50]), .Q (alu_result_in_stage_4[50]));
  DFQM2RA \alu_result_in_stage_4_reg[49] (.CK (clk), .D
       (alu_result_stage_3[49]), .Q (alu_result_in_stage_4[49]));
  DFQM2RA \alu_result_in_stage_4_reg[48] (.CK (clk), .D
       (alu_result_stage_3[48]), .Q (alu_result_in_stage_4[48]));
  DFQM2RA \alu_result_in_stage_4_reg[47] (.CK (clk), .D
       (alu_result_stage_3[47]), .Q (alu_result_in_stage_4[47]));
  DFQM2RA \pc_in_stage_3_reg[47] (.CK (clk), .D (pc_out_stage_2[47]),
       .Q (pc_in_stage_3[47]));
  DFQM2RA \alu_result_in_stage_4_reg[46] (.CK (clk), .D
       (alu_result_stage_3[46]), .Q (alu_result_in_stage_4[46]));
  DFQM2RA \alu_result_in_stage_4_reg[45] (.CK (clk), .D
       (alu_result_stage_3[45]), .Q (alu_result_in_stage_4[45]));
  DFQM2RA \read_data2_in_stage_3_reg[61] (.CK (clk), .D
       (read_data2_stage_2[61]), .Q (read_data2_in_stage_3[61]));
  DFQM2RA \alu_result_in_stage_4_reg[43] (.CK (clk), .D
       (alu_result_stage_3[43]), .Q (alu_result_in_stage_4[43]));
  DFQM2RA \pc_in_stage_2_reg[7] (.CK (clk), .D (pc_out_stage_1[7]), .Q
       (pc_in_stage_2[7]));
  DFQM2RA \pc_in_stage_3_reg[46] (.CK (clk), .D (pc_out_stage_2[46]),
       .Q (pc_in_stage_3[46]));
  DFQM2RA \read_data2_in_stage_3_reg[60] (.CK (clk), .D
       (read_data2_stage_2[60]), .Q (read_data2_in_stage_3[60]));
  DFQM2RA \alu_result_in_stage_4_reg[42] (.CK (clk), .D
       (alu_result_stage_3[42]), .Q (alu_result_in_stage_4[42]));
  DFQM2RA \alu_result_in_stage_4_reg[41] (.CK (clk), .D
       (alu_result_stage_3[41]), .Q (alu_result_in_stage_4[41]));
  DFQM2RA \read_data2_in_stage_3_reg[59] (.CK (clk), .D
       (read_data2_stage_2[59]), .Q (read_data2_in_stage_3[59]));
  DFQM2RA \alu_result_in_stage_4_reg[39] (.CK (clk), .D
       (alu_result_stage_3[39]), .Q (alu_result_in_stage_4[39]));
  DFQM2RA \pc_in_stage_3_reg[45] (.CK (clk), .D (pc_out_stage_2[45]),
       .Q (pc_in_stage_3[45]));
  DFQM2RA \read_data2_in_stage_3_reg[58] (.CK (clk), .D
       (read_data2_stage_2[58]), .Q (read_data2_in_stage_3[58]));
  DFQM2RA \alu_result_in_stage_4_reg[37] (.CK (clk), .D
       (alu_result_stage_3[37]), .Q (alu_result_in_stage_4[37]));
  DFQM2RA \read_data2_in_stage_3_reg[57] (.CK (clk), .D
       (read_data2_stage_2[57]), .Q (read_data2_in_stage_3[57]));
  DFQM2RA \alu_result_in_stage_4_reg[36] (.CK (clk), .D
       (alu_result_stage_3[36]), .Q (alu_result_in_stage_4[36]));
  DFQM2RA \pc_in_stage_2_reg[35] (.CK (clk), .D (pc_out_stage_1[35]),
       .Q (pc_in_stage_2[35]));
  DFQM2RA \pc_in_stage_2_reg[6] (.CK (clk), .D (pc_out_stage_1[6]), .Q
       (pc_in_stage_2[6]));
  DFQM2RA \pc_in_stage_3_reg[44] (.CK (clk), .D (pc_out_stage_2[44]),
       .Q (pc_in_stage_3[44]));
  DFQM2RA \read_data2_in_stage_3_reg[56] (.CK (clk), .D
       (read_data2_stage_2[56]), .Q (read_data2_in_stage_3[56]));
  DFQM2RA \alu_result_in_stage_4_reg[34] (.CK (clk), .D
       (alu_result_stage_3[34]), .Q (alu_result_in_stage_4[34]));
  DFQM2RA \alu_result_in_stage_4_reg[33] (.CK (clk), .D
       (alu_result_stage_3[33]), .Q (alu_result_in_stage_4[33]));
  DFQM2RA \read_data2_in_stage_3_reg[55] (.CK (clk), .D
       (read_data2_stage_2[55]), .Q (read_data2_in_stage_3[55]));
  DFQM2RA \alu_result_in_stage_4_reg[31] (.CK (clk), .D
       (alu_result_stage_3[31]), .Q (alu_result_in_stage_4[31]));
  DFQM2RA \pc_in_stage_3_reg[43] (.CK (clk), .D (pc_out_stage_2[43]),
       .Q (pc_in_stage_3[43]));
  DFQM2RA \read_data2_in_stage_3_reg[54] (.CK (clk), .D
       (read_data2_stage_2[54]), .Q (read_data2_in_stage_3[54]));
  DFQM2RA \alu_result_in_stage_4_reg[29] (.CK (clk), .D
       (alu_result_stage_3[29]), .Q (alu_result_in_stage_4[29]));
  DFQM2RA \read_data2_in_stage_3_reg[53] (.CK (clk), .D
       (read_data2_stage_2[53]), .Q (read_data2_in_stage_3[53]));
  DFQM2RA \alu_result_in_stage_4_reg[28] (.CK (clk), .D
       (alu_result_stage_3[28]), .Q (alu_result_in_stage_4[28]));
  DFQM2RA \pc_in_stage_2_reg[5] (.CK (clk), .D (pc_out_stage_1[5]), .Q
       (pc_in_stage_2[5]));
  DFQM2RA \pc_in_stage_3_reg[42] (.CK (clk), .D (pc_out_stage_2[42]),
       .Q (pc_in_stage_3[42]));
  DFQM2RA \read_data2_in_stage_3_reg[52] (.CK (clk), .D
       (read_data2_stage_2[52]), .Q (read_data2_in_stage_3[52]));
  DFQM2RA \alu_result_in_stage_4_reg[26] (.CK (clk), .D
       (alu_result_stage_3[26]), .Q (alu_result_in_stage_4[26]));
  DFQM2RA \alu_result_in_stage_4_reg[25] (.CK (clk), .D
       (alu_result_stage_3[25]), .Q (alu_result_in_stage_4[25]));
  DFQM2RA \read_data2_in_stage_3_reg[51] (.CK (clk), .D
       (read_data2_stage_2[51]), .Q (read_data2_in_stage_3[51]));
  DFQM2RA \alu_result_in_stage_4_reg[24] (.CK (clk), .D
       (alu_result_stage_3[24]), .Q (alu_result_in_stage_4[24]));
  DFQM2RA \pc_in_stage_3_reg[41] (.CK (clk), .D (pc_out_stage_2[41]),
       .Q (pc_in_stage_3[41]));
  DFQM2RA \read_data2_in_stage_3_reg[50] (.CK (clk), .D
       (read_data2_stage_2[50]), .Q (read_data2_in_stage_3[50]));
  DFQM2RA \alu_result_in_stage_4_reg[22] (.CK (clk), .D
       (alu_result_stage_3[22]), .Q (alu_result_in_stage_4[22]));
  DFQM2RA \read_data2_in_stage_3_reg[49] (.CK (clk), .D
       (read_data2_stage_2[49]), .Q (read_data2_in_stage_3[49]));
  DFQM2RA \alu_result_in_stage_4_reg[20] (.CK (clk), .D
       (alu_result_stage_3[20]), .Q (alu_result_in_stage_4[20]));
  DFQM2RA \alu_result_in_stage_4_reg[19] (.CK (clk), .D
       (alu_result_stage_3[19]), .Q (alu_result_in_stage_4[19]));
  DFQM2RA \pc_in_stage_2_reg[34] (.CK (clk), .D (pc_out_stage_1[34]),
       .Q (pc_in_stage_2[34]));
  DFQM2RA \pc_in_stage_2_reg[4] (.CK (clk), .D (pc_out_stage_1[4]), .Q
       (pc_in_stage_2[4]));
  DFQM2RA \pc_in_stage_3_reg[40] (.CK (clk), .D (pc_out_stage_2[40]),
       .Q (pc_in_stage_3[40]));
  DFQM2RA \read_data2_in_stage_3_reg[48] (.CK (clk), .D
       (read_data2_stage_2[48]), .Q (read_data2_in_stage_3[48]));
  DFQM2RA \alu_result_in_stage_4_reg[18] (.CK (clk), .D
       (alu_result_stage_3[18]), .Q (alu_result_in_stage_4[18]));
  DFQM2RA \alu_result_in_stage_4_reg[17] (.CK (clk), .D
       (alu_result_stage_3[17]), .Q (alu_result_in_stage_4[17]));
  DFQM2RA \read_data2_in_stage_3_reg[47] (.CK (clk), .D
       (read_data2_stage_2[47]), .Q (read_data2_in_stage_3[47]));
  DFQM2RA \alu_result_in_stage_4_reg[15] (.CK (clk), .D
       (alu_result_stage_3[15]), .Q (alu_result_in_stage_4[15]));
  DFQM2RA \pc_in_stage_3_reg[39] (.CK (clk), .D (pc_out_stage_2[39]),
       .Q (pc_in_stage_3[39]));
  DFQM2RA \read_data2_in_stage_3_reg[46] (.CK (clk), .D
       (read_data2_stage_2[46]), .Q (read_data2_in_stage_3[46]));
  DFQM2RA \alu_result_in_stage_4_reg[13] (.CK (clk), .D
       (alu_result_stage_3[13]), .Q (alu_result_in_stage_4[13]));
  DFQM2RA \read_data2_in_stage_3_reg[45] (.CK (clk), .D
       (read_data2_stage_2[45]), .Q (read_data2_in_stage_3[45]));
  DFQM2RA \alu_result_in_stage_4_reg[12] (.CK (clk), .D
       (alu_result_stage_3[12]), .Q (alu_result_in_stage_4[12]));
  DFQM2RA \pc_in_stage_2_reg[3] (.CK (clk), .D (pc_out_stage_1[3]), .Q
       (pc_in_stage_2[3]));
  DFQM2RA \pc_in_stage_3_reg[38] (.CK (clk), .D (pc_out_stage_2[38]),
       .Q (pc_in_stage_3[38]));
  DFQM2RA \read_data2_in_stage_3_reg[44] (.CK (clk), .D
       (read_data2_stage_2[44]), .Q (read_data2_in_stage_3[44]));
  DFQM2RA \alu_result_in_stage_4_reg[10] (.CK (clk), .D
       (alu_result_stage_3[10]), .Q (alu_result_in_stage_4[10]));
  DFQM2RA \alu_result_in_stage_4_reg[9] (.CK (clk), .D
       (alu_result_stage_3[9]), .Q (alu_result_in_stage_4[9]));
  DFQM2RA \read_data2_in_stage_3_reg[43] (.CK (clk), .D
       (read_data2_stage_2[43]), .Q (read_data2_in_stage_3[43]));
  DFQM2RA \alu_result_in_stage_4_reg[8] (.CK (clk), .D
       (alu_result_stage_3[8]), .Q (alu_result_in_stage_4[8]));
  DFQM2RA \pc_in_stage_3_reg[37] (.CK (clk), .D (pc_out_stage_2[37]),
       .Q (pc_in_stage_3[37]));
  DFQM2RA \read_data2_in_stage_3_reg[42] (.CK (clk), .D
       (read_data2_stage_2[42]), .Q (read_data2_in_stage_3[42]));
  DFQM2RA \alu_result_in_stage_4_reg[6] (.CK (clk), .D
       (alu_result_stage_3[6]), .Q (alu_result_in_stage_4[6]));
  DFQM2RA \read_data2_in_stage_3_reg[41] (.CK (clk), .D
       (read_data2_stage_2[41]), .Q (read_data2_in_stage_3[41]));
  DFQM2RA \alu_result_in_stage_4_reg[4] (.CK (clk), .D
       (alu_result_stage_3[4]), .Q (alu_result_in_stage_4[4]));
  DFQM2RA \alu_result_in_stage_4_reg[3] (.CK (clk), .D
       (alu_result_stage_3[3]), .Q (alu_result_in_stage_4[3]));
  DFQM2RA \pc_in_stage_2_reg[2] (.CK (clk), .D (pc_out_stage_1[2]), .Q
       (pc_in_stage_2[2]));
  DFQM2RA \pc_in_stage_3_reg[36] (.CK (clk), .D (pc_out_stage_2[36]),
       .Q (pc_in_stage_3[36]));
  DFQM2RA \read_data2_in_stage_3_reg[40] (.CK (clk), .D
       (read_data2_stage_2[40]), .Q (read_data2_in_stage_3[40]));
  DFQM2RA \alu_result_in_stage_4_reg[2] (.CK (clk), .D
       (alu_result_stage_3[2]), .Q (alu_result_in_stage_4[2]));
  DFQM2RA \alu_result_in_stage_4_reg[1] (.CK (clk), .D
       (alu_result_stage_3[1]), .Q (alu_result_in_stage_4[1]));
  DFQM2RA \read_data2_in_stage_3_reg[39] (.CK (clk), .D
       (read_data2_stage_2[39]), .Q (read_data2_in_stage_3[39]));
  DFQM2RA \alu_result_in_stage_4_reg[0] (.CK (clk), .D
       (alu_result_stage_3[0]), .Q (alu_result_in_stage_4[0]));
  DFQM2RA \pc_in_stage_3_reg[35] (.CK (clk), .D (pc_out_stage_2[35]),
       .Q (pc_in_stage_3[35]));
  DFQM2RA \read_data2_in_stage_3_reg[38] (.CK (clk), .D
       (read_data2_stage_2[38]), .Q (read_data2_in_stage_3[38]));
  DFQM2RA \read_data2_in_stage_4_reg[62] (.CK (clk), .D
       (read_data2_out_stage_3[62]), .Q (read_data2_in_stage_4[62]));
  DFQM2RA \read_data2_in_stage_3_reg[37] (.CK (clk), .D
       (read_data2_stage_2[37]), .Q (read_data2_in_stage_3[37]));
  DFQM2RA \read_data2_in_stage_4_reg[60] (.CK (clk), .D
       (read_data2_out_stage_3[60]), .Q (read_data2_in_stage_4[60]));
  DFQM2RA \read_data2_in_stage_4_reg[59] (.CK (clk), .D
       (read_data2_out_stage_3[59]), .Q (read_data2_in_stage_4[59]));
  DFQM2RA \pc_in_stage_3_reg[34] (.CK (clk), .D (pc_out_stage_2[34]),
       .Q (pc_in_stage_3[34]));
  DFQM2RA \read_data2_in_stage_3_reg[36] (.CK (clk), .D
       (read_data2_stage_2[36]), .Q (read_data2_in_stage_3[36]));
  DFQM2RA \read_data2_in_stage_4_reg[58] (.CK (clk), .D
       (read_data2_out_stage_3[58]), .Q (read_data2_in_stage_4[58]));
  DFQM2RA \read_data2_in_stage_4_reg[57] (.CK (clk), .D
       (read_data2_out_stage_3[57]), .Q (read_data2_in_stage_4[57]));
  DFQM2RA \read_data2_in_stage_3_reg[35] (.CK (clk), .D
       (read_data2_stage_2[35]), .Q (read_data2_in_stage_3[35]));
  DFQM2RA \read_data2_in_stage_4_reg[56] (.CK (clk), .D
       (read_data2_out_stage_3[56]), .Q (read_data2_in_stage_4[56]));
  DFQM2RA \read_data2_in_stage_4_reg[55] (.CK (clk), .D
       (read_data2_out_stage_3[55]), .Q (read_data2_in_stage_4[55]));
  DFQM2RA \pc_in_stage_3_reg[33] (.CK (clk), .D (pc_out_stage_2[33]),
       .Q (pc_in_stage_3[33]));
  DFQM2RA \read_data2_in_stage_3_reg[34] (.CK (clk), .D
       (read_data2_stage_2[34]), .Q (read_data2_in_stage_3[34]));
  DFQM2RA \read_data2_in_stage_4_reg[54] (.CK (clk), .D
       (read_data2_out_stage_3[54]), .Q (read_data2_in_stage_4[54]));
  DFQM2RA \read_data2_in_stage_4_reg[53] (.CK (clk), .D
       (read_data2_out_stage_3[53]), .Q (read_data2_in_stage_4[53]));
  DFQM2RA \read_data2_in_stage_4_reg[52] (.CK (clk), .D
       (read_data2_out_stage_3[52]), .Q (read_data2_in_stage_4[52]));
  DFQM2RA \read_data2_in_stage_4_reg[51] (.CK (clk), .D
       (read_data2_out_stage_3[51]), .Q (read_data2_in_stage_4[51]));
endmodule

